### ISSUE TITLE
Named Logger support

### ISSUE THREAD

**Issue by trevorreeves** [serilog/serilog-settings-configuration#1]
So my dream set of features for this would be:

a. Specify configuration for named loggers - sinks, logging levels, enrichers

b. Be able to specify and configure any sink (and of course all of their properties) for a named logger

c. A mechanism to configure a number of named loggers at once, according to some predicate (e.g. all named loggers for a given namespace - for use with `provider.CreateLogger<T>()`)

d. A default configuration used when the logger has no name, or when the name does not match any other name predicate in the configuration

e. Be able to adjust the logging level at runtime for any logger - named or nameless.

Serilog itself doesn't seem to have full support for (b) at the moment (for web.config), and the MFL Serilog Provider doesn't accommodate for the requirements around named loggers; for me, those are more important than supporting the IConfiguration abstraction in DNX.  Though IConfiguration support would be a nice bonus, and worth aiming for whilst doing this work.

**Comment by nblumhardt** [comment]
Hi Trevor; the first (rough) version of this is done; just getting it up to NuGet now.

There's a sample app included and some brief details on the README.

Now we're in action, would you mind raising individual tickets and/or PRs for these items, where you think they might be viable today given the Serilog/configuration capabilities as they stand? Seems like some great ideas here, will be tough to address in a single ticket however :-)

Looking forward to some feedback if you're able to check it out!

**Comment by trevorreeves** [comment]
Hi Nicholas, sorry for a delayed reply.  I am still interested in this, and I will take a look over the next week.

Thanks a lot.

Trevor.
