### ISSUE TITLE
Override minimum level for a sink

### ISSUE THREAD

**Issue by siberianguy** [serilog/serilog-settings-configuration#101]
I'm trying to set up two File sinks: for Verbose and Information minimum levels:

```
  "Serilog": {
    "MinimumLevel": {
      "Default": "Verbose"
    },
    "WriteTo": [{
      "Name": "File",
      "Args": { "path": "Log_Verbose.txt" }
    },{
      "Name": "File",
      "Args": { "path": "Log_Information.txt" },
      "restrictedToMinimumLevel": "Information"
    }]
  }
```
I found restrictedToMinimumLevel in this thread (https://github.com/serilog/serilog-settings-configuration/issues/70) but it doesn't seem to do what I expect: both files record Verbose. Seems like a basic feature (I used to have it in code), could you please hint me what I'm doing wrong?

**Comment by tsimbalar** [comment]
Hi Alexander,

the `restrictedToMinimumLevel` is an argument of the `WriteToFile(....., restrictedToMinimumLevel, ...)` method, so it needs to be specified as part of the `Args` json object.

The correct configuration would be something like : 

```json
  "Serilog": {
    "MinimumLevel": {
      "Default": "Verbose"
    },
    "WriteTo": [{
      "Name": "File",
      "Args": { "path": "Log_Verbose.txt", "restrictedToMinimumLevel": "Verbose" }
    },{
      "Name": "File",
      "Args": { "path": "Log_Information.txt", "restrictedToMinimumLevel": "Information" },
    }]
  }
```

(`restrictedToMinimumLevel` is not needed in the first case as its default value is `Verbose`, but explicitness does not hurt :) )

I hope it helps !

**Comment by siberianguy** [comment]
Omg, my bad. Thanks a lot!

**Comment by SaiSingamsetty** [comment]
> Hi Alexander,
> 
> the `restrictedToMinimumLevel` is an argument of the `WriteToFile(....., restrictedToMinimumLevel, ...)` method, so it needs to be specified as part of the `Args` json object.
> 
> The correct configuration would be something like :
> 
> ```json
>   "Serilog": {
>     "MinimumLevel": {
>       "Default": "Verbose"
>     },
>     "WriteTo": [{
>       "Name": "File",
>       "Args": { "path": "Log_Verbose.txt", "restrictedToMinimumLevel": "Verbose" }
>     },{
>       "Name": "File",
>       "Args": { "path": "Log_Information.txt", "restrictedToMinimumLevel": "Information" },
>     }]
>   }
> ```
> 
> (`restrictedToMinimumLevel` is not needed in the first case as its default value is `Verbose`, but explicitness does not hurt :) )
> 
> I hope it helps !

Hey,

I have tried it similarly, still showing the Verbose only, attaching you the piece of code and output

![Serilog1](https://user-images.githubusercontent.com/44539789/58644309-a14dd180-831e-11e9-87e3-f56e4851d1ca.PNG)

![Serilog2](https://user-images.githubusercontent.com/44539789/58644432-dce89b80-831e-11e9-955c-963f2734df59.PNG)


Can you please help me out.
