### ISSUE TITLE
Is it possible to set this Configuration key/value in Azure App Settings (or Environmental Vars?)

### ISSUE THREAD

**Issue by PureKrome** [serilog/serilog-settings-configuration#102]
Hi 👋 

Give this serilog configuration k/v's .. can this be set in Azure's App Settings or in Environmental Variables (which is what Azure does anyways):

Trying to set that Logentries `token` value.
It's the array, that's confusing me...

e.g. `appsettings.production.json`

```
 "Serilog": {
    "WriteTo": [
      {
        "Name": "Console"
      },
      {
        "Name": "Logentries",
        "Args": {
          "token": "SOME SECRET HERE",
          "outputTemplate": "{Level:u3}: {Message:lj}{NewLine}{Exception}"
        }
      }
    ]  
  }
```

**Comment by nblumhardt** [comment]
Hi @PureKrome 👋 

Yes, it's possible, although unfortunately it's not an optimal process right now; I believe given your config above, the variable name will be something like: `Serilog:WriteTo:1:Args:token` where the `1` is an index into the `WRITETO` array. May need some exploration; I seem to recall there's an example out there somewhere. HTH!

**Comment by lucasmaj** [comment]
I have similar need for AzureBlobStorage. Details here: https://github.com/chriswill/serilog-sinks-azureblobstorage/issues/47

I ended up with something similar to what is described here and then extended is some.

Basically I build the configuration twice. After first build of configuration I AddInMemoryCollection to overwrite the secrets/connectionstrings and use the second config to configure the logger.

Most importantly, I keep the paths ("Serilog:WriteTo:1:Args:connectionString") in appsettings.json and used that to know which keys to add in AddInMemoryCollection.

```c#
 var configurationBuilder = new ConfigurationBuilder()
                .AddJsonFile("appsettings.json", false, true)
                .AddEnvironmentVariables();

            IConfiguration configuration = configurationBuilder.Build();

            var pathsToInjectStorageConnectionString = configuration.GetSection("PathsToInjectStorageConnectionString").GetChildren().Select(section => section.Value);

            if (pathsToInjectStorageConnectionString.Any())
            {
                var storageConnectionString = new Dmp.Timelines.Backup(configuration["DmpAppStorageAccountName"], configuration["DmpAppStorageAccountKey"]).StorageAccount.ToString(true);
                configurationBuilder.AddInMemoryCollection(pathsToInjectStorageConnectionString.Select(path => new KeyValuePair<string, string>(path, storageConnectionString)));
                configuration = configurationBuilder.Build();
            }

            var loggerConfiguration = new LoggerConfiguration()
                .ReadFrom.Configuration(configuration);
```

**Comment by PureKrome** [comment]
@lucasmaj why build the config 2x. I didn't have to ....

**Comment by lucasmaj** [comment]
I guess in your situation the Serilog:WriteTo:1:Args:token was already an Environmental variable?

In my case the storage account name and key were two separate environment variables which needed to be combined into a connections string at run time.

**Comment by skomis-mm** [comment]
For a reference: 
- [Configuration: environment variables](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-3.1#evcp)
- [Configuration: bind an array](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-3.1#bind-an-array)

**Comment by PureKrome** [comment]
@SCC-BDuncan 

it's something like this:

given the configuration file snippet:

```
 "Serilog": {
    "WriteTo": [
      {
        "Name": "Console"
      },
      {
        "Name": "Logentries",
        "Args": {
          "token": "SOME SECRET HERE",
          "outputTemplate": "{Level:u3}: {Message:lj}{NewLine}{Exception}"
        }
      }
    ]  
  }
```

in your env-vars (like Azure App Service) you would have

| Key| Value | Notes |
|--------|--------|--------|
| `Serilog__WriteTo__1__Args__token` | `Some Secret Here`| Works on all OS's |
| `Serilog:WriteTo:1:Args:token` | `Some Secret Here`| Might not work on some OS's because the `:` is _reservered_|

**Comment by lucasmaj** [comment]
The solution I ended up with.

appsettings.json file

``` 
"Serilog": {
   "Using": [
     "Serilog.Sinks.AzureBlobStorage"
   ],
   "WriteTo": [
     {
       "Name": "AzureBlobStorage",
       "Args": {
         "outputTemplate": "[{Timestamp:u} {Level:u3} {SourceContext}] {Message:lj}{NewLine}{Exception}",
         "storageFileName": "logs/{yyyy}_{MM}/{dd}_{HH}.txt",
         "connectionStringName": "SerilogAzureBlobStorageConnectionString",
         "storageContainerName": "somecontainername"
       }
     }
   ]
 }
```

And then add connection string with matching name at runtime:

```
builder.Configuration.AddInMemoryCollection(new Dictionary<string, string?> { { 
   "ConnectionStrings:SerilogAzureBlobStorageConnectionString",  "SomeDynamicallyCreatedConnectionString"
} });
```
