### ISSUE TITLE
Minor issue relating to ConfigurationSection.Value property

### ISSUE THREAD

**Issue by MV10** [serilog/serilog-settings-configuration#103]
The way the package uses `ConfigurationSection.Value` has the potential to produce unexpected and incorrect behavior. I say "minor issue" because the configuration setup that would lead to this seems to be a very unlikely edge-case (or outright incorrect). I'm documenting it in case someone encounters it or feels like figuring out a fix. This will be more relevant once PR https://github.com/serilog/serilog-settings-configuration/pull/100 is merged.

In several places the code reads a configuration section, then tests the `Value` property for null. If it is not null, the code processes the property as a discrete string value. If the property is null, the code assumes an entire new configuration section has been retrieved (which may later be resolved as one of several complex types). The code always performs this test with an if/else structure.

The problem is that it's possible for _both_ scenarios to be true simultaneously: `Value` can have a discrete string value _and_ the section can have child entries. The MS Configuration package allows the application to overlay settings from multiple configuration sources. One source might assign a discrete value while a second source assigns a complex value.

I believe it's an edge-case because I can't think of a configuration scenario where that's likely to be needed.

In theory, something could take an `object` argument which could then accept a `string` or something like a `List<>`, but regardless, supplying two values for a single argument doesn't make any sense. There is no way to tell which was applied last, so we can't apply LIFO logic. Therefore I think the fix would be to throw an exception if both `Value` and `GetChildren().Any()` are provided for a single argument.

Offhand I don't remember what happens anywhere else this test is performed, so I'm unsure what may be needed to address those.

Up for grabs! 😀

**Comment by MV10** [comment]
@nblumhardt Does throwing an exception sound like a reasonable response, given that it's impossible to know which value should "win"? If so, I'll do a quick PR on this one.

**Comment by nblumhardt** [comment]
Throwing sounds reasonable for an edge-case like this - thanks Jon! :+1:

**Comment by MV10** [comment]
Thanks to some excellent review feedback from Ruben, the exception message is now very clear, I think.

> The value for the argument {argumentSection.Path} is assigned different value types in more than one configuration source. Ensure all configurations consistently use either a scalar (int, string, boolean) or a complex (array, section, list, POCO, etc.) type for this argument value.
