### ISSUE TITLE
Override Default Level Per Sink

### ISSUE THREAD

**Issue by clmcgrath** [serilog/serilog-settings-configuration#104]
I would like to limit one of my sinks to only log warnings and errors 
and have my other sinks log at the debug / verbose level 

In the c# api you can specify restrictedToMinimumLevel per sink 
is there a way to set this level via settings binding 

```
Log.Logger = new LoggerConfiguration()
    .MinimumLevel.Debug()
    .WriteTo.File("log.txt")
    .WriteTo.Console(restrictedToMinimumLevel: LogEventLevel.Information)
    .CreateLogger();
```

ie 
```
    "WriteTo": [
      {
        "Name": "Console", 
        "MinimumLevel" :  "Debug"
      },
```

**Comment by nblumhardt** [comment]
Hi!

```
    "WriteTo": [
      {
        "Name": "Console", 
        "Args": {"restrictedToMinimumLevel" :  "Debug"}
      },
```

should do it. HTH!

**Comment by clmcgrath** [comment]
works for me 👍 
i understand the reason for it after looking through how configuration is bound to the framework ,  but i would think this should be a top level configuration setting using a similar convention to the default setting

**Comment by nblumhardt** [comment]
Thanks for the follow-up and feedback, Chris 👍
