### ISSUE TITLE
Does default values override configuration from file?

### ISSUE THREAD

**Issue by simonkaspersen** [serilog/serilog-settings-configuration#113]
I have configured Serilog through `appsettings.json`, with `MinimumLevel` and some overrides. When adding `MinimumLevel` in the builder it may seems that it overrides what is read from the configurationfile.
Is this on purpose or is it a bug from my end?

In `appsettings.json` it has `MinimumLevel` of Warning, but it may seems that it goes back to `Verbose` again.

```csharp
loggerConfiguration
                .ReadFrom.Configuration(configurationFromAppSettings)
                .MinimumLevel.Verbose()
                .WriteTo.Logger(config => config
                    .MinimumLevel.Verbose()
                    .WriteTo.Console(outputTemplate: outputTemplate)
                    .WriteTo.RollingFile(Path.Combine(outputFolder, "testlog.log"),
                        outputTemplate: outputTemplate)
                    .Filter.ByExcluding(filteringExpression)
                    .Enrich.FromLogContext()
                    .Enrich.WithThreadId()
                    .Enrich.WithProperty("ApplicationId", AppSettings.ApplicationId))
                .WriteTo.Logger(config => config
                    .WriteTo
                    .RollingFile(Path.Combine(outputFolder, "profilinglog.log"),
                        outputTemplate: ProfilingHeader.SerilogTemplate)
                    .Filter.ByIncludingOnly(filteringExpression)
                    .Enrich.FromLogContext()
                    .Enrich.WithThreadId()
                    .Enrich.WithMachineName()
                    .Enrich.WithProperty("ApplicationId", AppSettings.ApplicationId)
                );
        }
```

**Comment by MV10** [comment]
That's sounds right, setting it later in the builder process would replace anything previously read from configuration. There isn't anything special about `ReadFrom.Configuration`, it's just another step in the process as far as the builder is concerned. I'd assume you could set `MinimumLevel.Verbose()` _before_ `ReadFrom.Configuration` and then config should override code.

**Comment by tsimbalar** [comment]
Closing, as it seems the issue has been resolved. 
Can be re-opened if needed ;)
