### ISSUE TITLE
Unable to add NuGet in an UWP app

### ISSUE THREAD

**Issue by Goldstrike** [serilog/serilog-settings-configuration#114]
Hello,

I work on an UWP app that uses a local **.Net Standard 1.3 Library**.

I've already added the following **NuGet** packages :

- `Serilog v.2.7.1`
- `Serilog.Sinks.File v.4.0.0`

I've updated the min version of the targetting app from **10.0.10586** to **10.0.14393**

But when I try to add the `Serilog.Setting.Configuration NuGet` package, I get the following error:

> Package Serilog.Settings.Configuration 2.6.1 is not compatible with uap10.0.14393 (UAP,Version=v10.0.14393) / win10-XXX. Package Serilog.Settings.Configuration 2.6.1 supports:
>   - net451 (.NETFramework,Version=v4.5.1)
>   - netstandard1.6 (.NETStandard,Version=v1.6)	

**_Is it normal? How could I update the .NET Standard version used by the UWP app?_**

**Comment by MV10** [comment]
Newer versions of the package actually require .NET Standard 2.0, which has been supported by UWP for since last year.

https://blogs.msdn.microsoft.com/dotnet/2017/10/10/announcing-uwp-support-for-net-standard-2-0/

**Comment by skomis-mm** [comment]
As @MV10 pointed, this package implements .NET Standard 2.0 so only 16299+ Windows builds are supported for UWP apps.
