### ISSUE TITLE
Question: appsettings.json and appsettings.environment.json for ASP.NET Core

### ISSUE THREAD

**Issue by lonix1** [serilog/serilog-settings-configuration#118]
ASP.NET Core `appsettings.json` files can be used additively for different environments, e.g.:

````csharp
.AddJsonFile("appsettings.json", optional:false)
.AddJsonFile("appsettings.Development.json", optional:true)
````
The latter adds to the former.

Let's say I always want file sink, but console sink only in development. So I add file sink to `appsettings.json` and console sink to `appsettings.Development.json`.

But in development, the result is that file sink is ignored. If I want it then I must add it to both files, which is a bad idea as copy-paste mistakes will happen one day.

Am I doing this correctly?

**Comment by MV10** [comment]
New key names are additive, but I believe duplicated key-names overwrite earlier values. So I think that should work as long as the development config's 'Using' references both sinks. You shouldn't need to copy the file sink settings, those will still be present from the production config.

**Comment by lonix1** [comment]
Not sure I understand. This is what I have:

For `appsettings.json`:
````json
"WriteTo": [
  { "Name": "File", "Args": { "path": "log.txt" } }
]
````
For `appsettings.Development.json`:
````json
"WriteTo": [
  { "Name": "Console" }
]
````

In development, it does not write to file sink, but does write to console.

So are you saying that it replaced (not added) to that array? If so is there a way to make it work without duplicating?

**Comment by lonix1** [comment]
I just verified that it is additive in other parts of the `appsettings.json` but not here. I think it's because it's an array, and the array is replaced.

So this doesn't work, at least for me. If anyone has a workaround, I'd appreciate it.

**Comment by skomis-mm** [comment]
@lonix1 json array syntax is a syntatic sugar here.
```json
"WriteTo": [
  { "Name": "File", "Args": { "path": "log.txt" } }
]
```
is equal to:
```json
`"WriteTo:0":  {
   "Name": "File", "Args": { "path": "log.txt" } 
}
```
where `0` is element index in the array. `Microsoft.Extension.Configuration` is build around key-value dictionary so each configuration key must have unique name. 
So in your case you overwrite the first element in the `appsettings.Development.json`. Workaround will be any other name (not `0`):
```json
"WriteTo:1": {
   "Name": "Console" 
}
```
```json
"WriteTo:MyConsole": {
   "Name": "Console" 
}
```
```json
"WriteTo:Whatever": {
   "Name": "Console" 
}
```

**Comment by lonix1** [comment]
Problem is it now gives `System.InvalidOperationException: The configuration value in Serilog:WriteTo:0:Name has no 'Name' element.`

However when I remove the array then it works. Since I'm only using one sink in that configuration, it's good enough for me. Thanks.
