### ISSUE TITLE
RollingFile-Example

### ISSUE THREAD

**Issue by code1line** [serilog/serilog-settings-configuration#12]
Can you provide an configuration-example for the RollingFile-Sink?

**Comment by code1line** [comment]
I figured it out! :-)

**Comment by merbla** [comment]
Hi @code1line,
We are keen to improve our doco.  Was there anything in particular the documentation was missing?

**Comment by code1line** [comment]
You can explain, that the keys from the Args-object matches the Sink-parameters, e.g. pathFormat for the filenames within the RollingFile-sink.
