### ISSUE TITLE
Issue : System.Runtime version 4.0.20.0 could not be loaded.

### ISSUE THREAD

**Issue by jagrutichavan** [serilog/serilog-settings-configuration#127]
This issue occurs after introducing Serilog.Sinks.Network nuget package in .Net Framework 4.6

**Comment by jagrutichavan** [comment]
![serilogissue](https://user-images.githubusercontent.com/21359247/44568890-2c99a580-a796-11e8-985b-c94b03b43df6.PNG)

**Comment by MV10** [comment]
I don't really work with .NET Framework any more, but what makes you think it's related to config?
Wouldn't this make more sense in the [Network sink repo](https://github.com/pauldambra/Serilog.Sinks.Network)?

**Comment by MV10** [comment]
Closing as it doesn't appear to be related to this package. We can reopen if that isn't the case.
