### ISSUE TITLE
Help with destructuring

### ISSUE THREAD

**Issue by FabianB1998** [serilog/serilog-settings-configuration#129]
The code `Log.Information("Gespräch {@Gesp} wurde angelegt", offerd);` outputs 

> Gespräch Gespraech {  } wurde angelegt

into the File Sink. 

The Console Sink provides a different output:

> Gespräch {"$type": "Gespraech"} wurde angelegt

Do I need to provide additional Destructuring Information for it to succeed correctly?
The class for offerd is defined as followed and is initialized with values. 

```csharp
    [Serializable]
    public class Gespraech : Networkable
    {
        public string AngerufeneNummer;
        public string AnruferNummer;
        public string Anschluss;

        public DateTime BeginnDateTime;
        public DateTime EndDateTime;
    }
```

**Comment by FabianB1998** [comment]
Sorry, I cant seem to get the class code snippet to format properly

**Comment by MV10** [comment]
@FabianB1998 use three backticks to begin/end code blocks. You can put the syntax on the line with the first three backticks (csharp, xml, etc)

Destructure is looking for properties, not fields:

```csharp
public class Gespraech : Networkable
{
   public string AngerufeneNummer { get; set; }
   // etc...
}
```

It doesn't require the `[Serializable]` attribute.

**Comment by FabianB1998** [comment]
Thanks a lot, I just noticed I created this Issue in the wrong repo, sorry for that :)
