### ISSUE TITLE
Extension methods with IConfiguration parameter are ignored

### ISSUE THREAD

**Issue by andriysavin** [serilog/serilog-settings-configuration#142]
When you define sink configuration extension method with `IConfiguration` parameter that method is ignored. At the same time if you use `IConfigurationSection` and specify value in config source, the method is discovered and the parameter is populated. Also, if default value (null) is specified for `IConfiguration` parameter all works as exepected as well. I believe the source of the problem lies in the code which filters methods and doesn't take into account `IConfiguration` parameter type: https://github.com/serilog/serilog-settings-configuration/blob/51a4fca7cf125adc717b657afa98ea8db2fddaea/src/Serilog.Settings.Configuration/Settings/Configuration/ConfigurationReader.cs#L351

**Comment by nblumhardt** [comment]
Thanks for the report, sounds like something was overlooked 👍

**Comment by MV10** [comment]
I don't think it's a bug in the config package.. The SQL sink relies on this to find a named connectionstring in a section outside of the Serilog-specific section. Using the dev version of the SQL sink and the 3.0.0 release of the config package, this code and config works and is probably the simplest way to reproduce this without writing your own sink:

```csharp
var appConfig = new ConfigurationBuilder()
    .SetBasePath(Directory.GetCurrentDirectory())
    .AddJsonFile(path: "appsettings.json")
    .Build();

var logConfig = new LoggerConfiguration();
logConfig.ReadFrom.Configuration(appConfig);
Log.Logger = logConfig.CreateLogger();
Serilog.Debugging.SelfLog.Enable(Console.Error);

Log.Information("An Information message");

Log.CloseAndFlush();
```

```json
{
  "ConnectionStrings": {
    "DevTest": "Data Source=(LocalDB)\\MSSQLLocalDB;Initial Catalog=SerilogTest;Integrated Security=true"
  },
  "Serilog": {
    "Using": [ "Serilog.Sinks.Console" ],
    "WriteTo": [
      { "Name": "Console" },
      {
        "Name": "MSSqlServer",
        "Args": {
          "connectionString": "DevTest",
          "tableName": "Issue81",
          "autoCreateSqlTable":  true,
          "columnOptionsSection": {
            "customColumns": [
              {
                "ColumnName": "EventType",
                "DataType": "int"
              },
              {
                "ColumnName": "Release",
                "DataType": "varchar",
                "DataLength": 32
              }
            ]
          }
        }
      }
    ]
  }
}
```

**Comment by andriysavin** [comment]
@MV10 If you look at the source code of that sink (configuration part), you'll see it assigns a default value `null` to configuration parameter:

https://github.com/serilog/serilog-sinks-mssqlserver/blob/40e3919ec448f3f5d8673b1a0a9fd959b349099b/src/Serilog.Sinks.MSSqlServer/Configuration/Microsoft.Extensions.Configuration/LoggerConfigurationMSSqlServerExtensions.cs#L57

So this proves what I wrote.

**Comment by MV10** [comment]
@andriysavin The default value is irrelevant. It works because the SQL sink is able to resolve the named connection string, which is outside of the Serilog section. This means the full `IConfiguration` parameter was populated correctly.

**Comment by andriysavin** [comment]
@MV10 correct, but if that parameter is not assigned default value, the method is not called. Try it yourself.

**Comment by MV10** [comment]
@andriysavin Ah, I missed that part when I read your original mesage, sorry about that. Weird. I'll take a look.

**Comment by tsimbalar** [comment]
@andriysavin @MV10 I could reproduce that behavior (and fix it) as part of https://github.com/serilog/serilog-settings-configuration/pull/144.

This should generate a new pre-release of *Serilog.Settingc.Configuration* v3.0.1-devXXX

**Comment by tsimbalar** [comment]
Package v3.0.1 has now been released - https://www.nuget.org/packages/Serilog.Settings.Configuration/3.0.1

Thanks for your report !

**Comment by andriysavin** [comment]
Note that this turns out to be a breaking change for the code which used workaround with assigning default value. In this case the configuration parameter remains null (but the method is now called). For example, if SQL Server sink we [discussed](https://github.com/serilog/serilog-settings-configuration/issues/142#issuecomment-429215971) above upgrades this package to 3.0.1, I believe it will always get null in `appConfiguration` parameter.
