### ISSUE TITLE
Add config overloads to pass both a `IConfigSection` and `IConfiguration`

### ISSUE THREAD

**Issue by tsimbalar** [serilog/serilog-settings-configuration#148]
Right now, when calling `ReadFrom.ConfigSection(IConfigurationSection configSection)`, the `ConfigurationReader` does not have access to the *global* `IConfiguration` object, so it cannot access the configuration out of the given section. That makes it impossible to access, say, the `ConnectionStrings` ... . 

In PR #144 we added a check to throw an exception when calling a config method that expects an `IConfiguration` from the `ReadFrom.ConfigSection` overload so that users don't shoot themselves in the foot.

We should probably mark `ConfigurationSection(this LoggerSettingsConfiguration settingConfiguration /*, ...*/)` methods as obsolete and instead provide new overloads like

```csharp
ReadFrom.ConfigurationSection(
  this LoggerSettingsConfiguration settingConfiguration, 
  IConfiguration configuration, 
  string sectionName /*, ...*/)
```
this would store the global `IConfiguration` object and look for a section with a given name within.

Does that seem to make sense ? 

See https://github.com/serilog/serilog-settings-configuration/issues/143 for more details

**Comment by MV10** [comment]
Haven't had time to look at the code yet, but based on the issue that brought up the problem, I assume the exception is only thrown if the parameter doesn't have a default value?

**Comment by tsimbalar** [comment]
@MV10 good catch ! I had missed that case. 

Just created a PR to fix it : https://github.com/serilog/serilog-settings-configuration/pull/149
