### ISSUE TITLE
ConfigurationReader in Android throw exceptions.

### ISSUE THREAD

**Issue by Lukiya** [serilog/serilog-settings-configuration#150]
ConfigurationReader.cs line 312.

[query = from outputAssemblyPath in System.IO.Directory.GetFiles(AppDomain.CurrentDomain.BaseDirectory, "*.dll")](https://github.com/serilog/serilog-settings-configuration/blob/dev/src/Serilog.Settings.Configuration/Settings/Configuration/ConfigurationReader.cs#L312)

**_AppDomain.CurrentDomain.BaseDirectory_** cannot be used in Android platform, it always return null.
Due to this, a System.ArgumentNullException will be thrown out.

**Comment by MV10** [comment]
I'm betting this would also fail on iOS (though I have no way to test this).

**Comment by Lukiya** [comment]
Fortunately, iOS doesn't have this issue. Here is how I get the base directory in android.
I pass the main entry class type into my app, and use that type to get its location, it works pretty well.

```
private string GetBinDirectory(Type entryPointType = null)
{
    if (null!= entryPointType)
    {
        var binDirectory = Path.GetDirectoryName(entryPointType.Assembly.Location);
    }
    else
    {
        var binDirectory = AppDomain.CurrentDomain.BaseDirectory;
    }
    return binDirectory;
}
```

**Comment by tsimbalar** [comment]
This should get easier to implement once the refactorings in PR https://github.com/serilog/serilog-settings-configuration/pull/151 are merged.
