### ISSUE TITLE
Changelog is outdated

### ISSUE THREAD

**Issue by andre-ss6** [serilog/serilog-settings-configuration#152]
Changelog only has changes for versions 2.0 and 2.1. The project has recently increased its major version (to 3.0), which seems to indicate a breaking change. However, there seems to be no documentation whatsoever as to what changed.

**Comment by tsimbalar** [comment]
Hi @andre-ss6 , 

Do the details in the *release* help ? : https://github.com/serilog/serilog-settings-configuration/releases/tag/v3.0.0

**Comment by andre-ss6** [comment]
Yea, I had seen that. It helps a little. But it would be nice if at least breaking changes were documented. Having to read through PRs just to know why the major version was bumped is a little cumbersome. I just want to know if there was any breaking change and if yes, which one.

Thanks anyway :)

**Comment by skomis-mm** [comment]
Changelog updated
