### ISSUE TITLE
Question: can I logging only specific categories

### ISSUE THREAD

**Issue by WeihanLi** [serilog/serilog-settings-configuration#164]
can I logging only specific categories, for example, log things happened in some modules only

**Comment by tsimbalar** [comment]
Yes, you could use `Filter`, which would prevent from emitting some logging events that match some criteria. 

The https://github.com/serilog/serilog-filters-expressions package could be quite helpful. 

If you are logging with "class loggers" (`Log.ForContext<MyType>`), then you will find a `SourceContext` property on your log events, and you can use it to filter.

Here is an example of configuration : https://github.com/tsimbalar/serilog-settings-comparison/blob/master/docs/README.md#filtering---expressions

I hope this helps !

**Comment by WeihanLi** [comment]
Yeah, thanks very much.  Awesome serilog.
