### ISSUE TITLE
Is it possible to specify value for named parameters of constructor

### ISSUE THREAD

**Issue by vhatsura** [serilog/serilog-settings-configuration#167]
Hey, guys!

In some case I need to specify named parameters of constructor (in most cases, it's needed for custom formatters).
Let's see it on a simple example.
To use custom formatter with Console sink we can use the following configuration:

```json
{
  "Serilog": {
    "WriteTo": [
      {
        "Name": "Console",
        "Args": {
          "formatter": "JsonValueFormatter "
        }
      }
    ]
  }
}
```

Is it possible to somehow in above example to specify [`typeTagName`](https://github.com/serilog/serilog/blob/9a46e68d3e224b965f4ac2665fd379ae9568d6b4/src/Serilog/Formatting/Json/JsonValueFormatter.cs#L39) parameter of constructor?  

If it isn't possible to do, I will appreciate for ability to implement such functionality by myself.

**Comment by tsimbalar** [comment]
Hi Vadim,

no it is not currently supported :-/ 
There has been a similar request here, with a proposed workaround if that works for you : https://github.com/tsimbalar/serilog-settings-comparison/issues/1

**Comment by vhatsura** [comment]
Hi, @tsimbalar.

Thanks for the link. The proposed workaround is interisting and can be helpful, however not in all scenario.

As an example, for [ExceptionAsObjectJsonFormatter from Serilog.Formatting.Elasticsearch package](https://github.com/serilog/serilog-sinks-elasticsearch/blob/f38b376b7fb629c07c45a8573823d86fd858a4fe/src/Serilog.Formatting.Elasticsearch/ExceptionAsObjectJsonFormatter.cs#L46) it can be hard to precreate formatters with all possible combinations.
