### ISSUE TITLE
Start Failure Error

### ISSUE THREAD

**Issue by hbergun** [serilog/serilog-settings-configuration#168]
Version:Asp.Net Core 2.2
> var configuration = new ConfigurationBuilder()
            .AddJsonFile("appsettings.json")
            .Build();

the above code block causes an error, I followed the documentation but did not solve this problem,I think should be edit in the startup file

**Comment by nblumhardt** [comment]
Hi - what does the error look like? Thanks!

**Comment by hbergun** [comment]
> Hi - what does the error look like? Thanks!

HTTP Error 500.30 Start Failure
I think should be edit in the startup file but I couldnt solve the problem Thank You

**Comment by nblumhardt** [comment]
Unfortunately this isn't enough to work with - you'll need to find a stack trace/developer error message somewhere before the cause will be able to be tracked down.

**Comment by hbergun** [comment]
error details that I could find

Unhandled Exception: System.IO.FileNotFoundException: The configuration file 'appsettings.json' was not found and is not optional. The physical path is 'C:\Path\bin\Debug\netcoreapp2.2\appsettings.json'.
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at SerilogExercise.Program.Main(String[] args) in C:\Path\SerilogExercise\SerilogExercise\Program.cs:line 20

thank you.

**Comment by hbergun** [comment]
> Unfortunately this isn't enough to work with - you'll need to find a stack trace/developer error message somewhere before the cause will be able to be tracked down.

I solved this problem,the way I followed;
```C#
var config = new ConfigurationBuilder()
                .SetBasePath(@"The path where the appsettings.json file is located ex: 
                                             C:\Users\USERNAME\source\repos\SerilogExercise\")

                .AddJsonFile("appsettings.json")
                .Build();
```

and 
```JSON
 "Destructure": [
      //{
      //  "Name": "With",
      //  "Args": { "policy": "Sample.CustomPolicy, Sample" }
      //},
      {
        "Name": "ToMaximumDepth",
        "Args": { "maximumDestructuringDepth": 4 }
      },
      {
        "Name": "ToMaximumStringLength",
        "Args": { "maximumStringLength": 100 }
      },
      {
        "Name": "ToMaximumCollectionCount",
        "Args": { "maximumCollectionCount": 10 }
      }
    ],
```
I removed the lines above("Name":"With")
I think the document needs updating because he stole my time. Thank you I hope this helps

**Comment by nblumhardt** [comment]
Great, glad you were able to figure it out.

The correct path to the JSON config file will depend on the app and on the hosting model, so we might add a note rather than change the example code 👍
