### ISSUE TITLE
TypeLoadException was not handled by user code

### ISSUE THREAD

**Issue by Sphiecoh** [serilog/serilog-settings-configuration#17]
I am getting the below error when trying to load config.

Project.json :
```
 "dependencies": {
"Serilog.Framework.Logging": "1.0.0-rc1-final-10075",
    "valueinjecter": "3.1.1.2",
    "Serilog.Sinks.RollingFile": "2.1.0",
    "Online.Mvc": "2.0.0-alpha-0022",
    "Serilog.Settings.Configuration": "2.0.0",
    "Serilog.Enrichers.Thread": "2.0.0",
    "Serilog.Enrichers.Environment": "2.0.1"
  },
  "frameworks": {
    "net451": {
      "buildOptions": {"preserveCompilationContext": true}
    }
```
applicationsettings.json :
```
"Serilog": {
    "Using": [ "Serilog.Sinks.RollingFile" ],
    "MinimumLevel": "Debug",
    "WriteTo": [
      {
        "Name": "RollingFile",
        "Args": { "pathFormat": "logs\\log-{Date}.log" }
      }
    ],
    "Enrich": [ "WithMachineName", "WithThreadId" ]
  }
```

Additional information: Method 'Log' in type 'Serilog.Framework.Logging.SerilogLogger' from assembly 'Serilog.Framework.Logging, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.

**Comment by nblumhardt** [comment]
Hi Sifiso,

The package you need is now named `Serilog.Extensions.Logging`, not `Serilog.Framework.Logging`. You can check out some of the setup details at:

https://github.com/serilog/serilog-extensions-logging

Hope this helps,
Nick

**Comment by Sphiecoh** [comment]
Thank you
