### ISSUE TITLE
Override Map not applying correctly

### ISSUE THREAD

**Issue by prindacerk** [serilog/serilog-settings-configuration#172]
Hi have 2 appsettings in my ASP.NET Core project. Default is Production and override is Development.
I have the following code in my configs.
In appsettings.json,

```json
"Serilog": {
	"Using": [ "Serilog.Sinks.Async", "Serilog.Sinks.RollingFile" ],
	"MinimumLevel": {
	  "Default": "Information",
	  "Override": {
		"Microsoft": "Warning",
		"System": "Error"
	  }
	},
	"WriteTo": [
	  {
		"Name": "RollingFile",
		"Args": {
		  "pathFormat": "C:/Logfiles/project/log-{Date}.json",
		  "formatter": "Serilog.Formatting.Json.JsonFormatter, Serilog",
		  "fileSizeLimitBytes": 2147483648,
		  "retainedFileCountLimit": 5
		}
	  }
	],
	"Properties": {
	  "Application": "ServiceMyCar.Web.Api"
	}
}
```

And the overriding appsettings.development.json,

```json
"Serilog": {
	"MinimumLevel": {
	  "Default": "Debug",
	  "Override": {
		"Microsoft": "Information",
		"System": "Information"
	  }
	}
}
```

So from my understanding, in Development environment, the MinimumLevel should be **Debug**. In Production environment, the MinimumLevel should be **Information**. However, for some reason the overriding configuration is not applying. I have attached the output.
![Serilog](https://user-images.githubusercontent.com/4536573/55669163-ce05df80-58bf-11e9-9010-a3649124c507.png)

As you can see in the image, HasOverrideMap is true (marked by blue). The LevelSwitch (marked by green) is showing MinimumLevel of the appsettings.json value. And the configuration from appsettings.development.json is loaded under the OverrideMap values. So the configuration has been loaded into the Logger. But in the IsEnabled check, the level for Debug is false. Which means the OverrideMap is not applying. And that's why I am not seeing the Debug messages from my application.

Can someone help me figure out why this is happening and how I can resolve this problem? I am using latest Serilog versions and using ASP.NET Core 2.2.

**Comment by jmck-contessa** [comment]
I don't know that this will fix your problem, but the `Serilog.Sinks.File` sink now has rolling capabilities and improved functionality. `Serilog.Sinks.RollingFile` has essentially been deprecated. I would first start by converting to the `File` sink and seeing if that improves your situation. You can see more info at the top of the [README](https://github.com/serilog/serilog-sinks-rollingfile/blob/dev/README.md).

**Comment by prindacerk** [comment]
@jmck-contessa Thanks. But that is not the cause of my problem.
Further investigation gave me more insight into my problem.

If I use the globally shared logger via `Serilog.Log.Logger`, I get the configuration driven logger. Or if I use `Serilog.Log.ForContext("RequestHost", context?.Request?.Host)`, it still uses the configuration.

But if I use `Serilog.Log.ForContext<HttpContext>()`, it creates a new instance which seems to work with default setup and not the configuration driven logging. Somehow the configuration is being ignored for this case.

**Comment by tsimbalar** [comment]
Just to be sure there is no misunderstanding, let me explain what you are doing, and then you can confirm that it is indeed what you are trying to achieve :)  

When you do `Log.ForContext<HttpContext>`, this is pretty much equivalent to  `Log.ForContext("SourceContext", "Microsoft.AspNetCore.Http.HttpContext")`, i.e. you are adding a property named `SourceContext` whose value is the full namespaced-name of the type you pass to the type parameter `T` in `.ForContext<T>`. At first glance, this seems a bit strange, as you would normally use `.ForContext<T>` where `T` is a type you *own*. This is typically used to be able to track down which class wrote which log events.

It is the property `SourceContext` that is taken into account also for "[Level Overrides](https://nblumhardt.com/2016/07/serilog-2-minimumlevel-override/)". As far as I understand, you are therefore writing some of your logs with `SourceContext = "Microsoft.AspNetCore.Http.HttpContext"`, but you have defined some Level Overrides that state that for `SourceContext` starting with `Microsoft.*`, only write logs when the event level is `> Information` .... 

Would this explain what you are seeing ? 

If what you are trying to do is attach some properties of the `HttpContext` to the events you are logging, the expected approach would be to use the form you described later in you description : `Serilog.Log.ForContext("RequestHost", context?.Request?.Host)` .

If you really want to attach all the properties of `HttpContext`, then you should be using : 

```cs
Serilog.Log.ForContext("HttpContext", context, destructureObjects: true)
``` 

but this is really not recommended :P

**Comment by olicooper** [comment]
I am having the same issue. 

1. Application is deployed and running on a production environment with `appsettings.json` and `appsettings.Production.json`.
1. During application execution I update the `appsettings.Production.json` to debug an issue with a particular class, so I **add a new entry** to the minimum level overrides for `"MyProject.MyClass": "Verbose"`.
In this scenario serilog does not pick up the additional override. I have also tried adding it to `appsettings.json` too. If I stop the application and start it again, the configuration is correctly picked up, but I can't do this in production.

My environment:
* AspNetCore: v3.1.3
* Serilog.AspNetCore: v3.2.0
* Serilog.Settings.Configuration: v3.1.0
* Serilog.Sinks.File: v4.1.0

`IConfiguration` is set using `Microsoft.Extensions.Hosting.Host.CreateDefaultBuilder(args)` so `appsettings.Production.json` replaces the default `appsettings.json` and automatically reloads during application execution ([see the source code](https://github.com/dotnet/extensions/blob/v3.1.3/src/Hosting/Hosting/src/Host.cs#L74-L75))

Examples:

appsettings.json
```
"MinimumLevel": {
  "Default": "Debug",
  "Override": {
    "Microsoft": "Warning",
    "System": "Warning"
  }
}
```

appsettings.Production.json
```
"MinimumLevel": {
  "Default": "Information",
  "Override": {
    "Microsoft": "Error",
    "MyProject.MyClass": "Verbose" <-- add this during program execution
  }
}
```

**Comment by tsimbalar** [comment]
@olicooper 

In your second example, the "default" `MinimumLevel` is `Information`, meaning that any event of level `< Information` is discarded completely from the logging _pipeline_ . If you set an override to a level lower than that, this will have no effect.

If you do : 

```json
"MinimumLevel": {
  "Default": "Verbose", <-- I changed this
  "Override": {
    "Microsoft": "Error",
    "MyProject.MyClass": "Verbose" <-- add this during program execution
  }
}
```

then I guess you'd see the logs from `Project.MyClass` (and probably a lot of `debug` or `verbose` entries ;))

**Comment by skomis-mm** [comment]
Hi @olicooper ,

**adding new entry** in override section is not supported for a live update (niether in code nor in file settings). 
The workaround is to add category `MyProject.MyClass` with default level (`Information`) upfront. After that you can change "Information" to "Verbose" for that category during execution.

**Comment by olicooper** [comment]
@skomis-mm yeah it didn't seem to be supported, that's a shame. I will do this then thank you 👍
