### ISSUE TITLE
Security vulnerability

### ISSUE THREAD

**Issue by emh-rowland-oconnor** [serilog/serilog-settings-configuration#173]
**URGENT**

appveyor.yml contains nuget API publish secret keys.

Anyone with bad intent could publish their own version of the package into the Serilog nuget feed.

**Comment by tsimbalar** [comment]
Hi Rowland,

thanks for dropping by.

Unless I'm totally mistaken, the key that appears in the `appveyor.yaml` is not the "plain" Nuget publish key. It is encrypted with AppVeyor's key, so it cannot be used "as is" to publish to Nuget.

**Comment by emh-rowland-oconnor** [comment]
Hey @tsimbalar 

Thank you.

I raised this because the key looks very similar in format and length to my own (unencrypted) Nuget key.

If you are sure the key is encrypted, I'm happy.

**Comment by nblumhardt** [comment]
Phew! That's a title that grabs my attention :-D

Thanks for the heads-up, @emh-rowland-oconnor - much appreciated. As @tsimbalar suggests, in AppVeyor any `secure:` values are encrypted (AES 265 IIRC).
