### ISSUE TITLE
%AppData% folder not correctly replaced in appsettings.json

### ISSUE THREAD

**Issue by fleed** [serilog/serilog-settings-configuration#175]
I have the following `appsettings.json`:

```
"Serilog": {
    "Using":  [ "Serilog.Sinks.File" ],
    "MinimumLevel": "Debug",
    "WriteTo": [
      { "Name": "File", "Args": { "path": "%APPDATA%\\CompanyName\\ApplicationName.txt", "rollingInterval": "Day", "fileSizeLimitBytes": 26214400, "rollOnFileSizeLimit":  true } }
    ],
    "Enrich": [ "FromLogContext", "WithMachineName", "WithThreadId" ],
    "Destructure": [
      { "Name": "ToMaximumDepth", "Args": { "maximumDestructuringDepth": 4 } },
      { "Name": "ToMaximumStringLength", "Args": { "maximumStringLength": 100 } },
      { "Name": "ToMaximumCollectionCount", "Args": { "maximumCollectionCount": 10 } }
    ],
    "Properties": {
      "Application": "Name"
    }
  },
```

and I initialize Serilog reading the resulting configuration.
Anyway, the result is not exactly what I would expect (using the `AppData` system folder). I get instead an `%AppData%` folder created and containing the logs:

![image](https://user-images.githubusercontent.com/2131800/54424425-20b20880-4713-11e9-9402-64877ae31f7c.png)

**Comment by mishrapw** [comment]
Hi @nblumhardt,
Is this still open, do we have alternative approach to get "AppData" or custom path File write using JSON configuration file.

**Comment by nblumhardt** [comment]
@mishrapw still open

**Comment by skomis-mm** [comment]
Hi, @fleed , @mishrapw , @nblumhardt . Actually, it should work (just tested), see
https://github.com/serilog/serilog-settings-configuration/blob/dev/src/Serilog.Settings.Configuration/Settings/Configuration/StringArgumentValue.cs#L31
and sample:

what version of the package do you use?

**Comment by mishrapw** [comment]
Thanks @skomis-mm , It works.

**Comment by nblumhardt** [comment]
Aha! I'd forgotten about the progress on this, sorry :-)
