### ISSUE TITLE
Minimum Level not picking the correct value from appsettings.json

### ISSUE THREAD

**Issue by SaiSingamsetty** [serilog/serilog-settings-configuration#180]
I am trying to create a logger configuring from json file. I have written the below piece of code.
I have mentioned 'Debug' as default Minimum Level but it is considering 'Verbose' only. Please let me know if i am missing anything or configuring incorrectly.

![Serilog1](https://user-images.githubusercontent.com/44539789/58653846-39a28100-8334-11e9-89e3-2c52a1797424.PNG)
![Serilog2](https://user-images.githubusercontent.com/44539789/58653927-72daf100-8334-11e9-910e-4becf2f76554.PNG)
![image](https://user-images.githubusercontent.com/44539789/58654424-7de25100-8335-11e9-90c5-4585d0da5966.png)

**Comment by tsimbalar** [comment]
Hi,

I see you are doing 

```cs
.ReadFrom.ConfigurationSection(Configuration.GetSection("Serilog"))
```

`"Serilog"` is the default section name we use, so you should be able to do : 

```cs
.ReadFrom.Configuration(Configuration)
```

Does that change anything ? (it shouldn't, but who knows :P )

Also some information about which versions of the packages you are using would be helpful :)

**Comment by nblumhardt** [comment]
Hi @SaiSingamsetty - what happens when you log a `Verbose` event? I.e. does it show up at sinks? Thanks!

**Comment by SaiSingamsetty** [comment]
> Hi,
> 
> I see you are doing
> 
> ```cs
> .ReadFrom.ConfigurationSection(Configuration.GetSection("Serilog"))
> ```
> 
> `"Serilog"` is the default section name we use, so you should be able to do :
> 
> ```cs
> .ReadFrom.Configuration(Configuration)
> ```
> 
> Does that change anything ? (it shouldn't, but who knows :P )
> 
> Also some information about which versions of the packages you are using would be helpful :)

I tried with .ReadFrom.Configuration(Configuration) also, it still shows the same output.
FYI, I am using 
![image](https://user-images.githubusercontent.com/44539789/58684386-bc0f5d00-8395-11e9-87ea-d6bef070aa9b.png)


It is not picking correctly when I use Configuration from JSON file.

I tried writing code to configure Logger whereas it worked well.
![image](https://user-images.githubusercontent.com/44539789/58684322-82d6ed00-8395-11e9-8e7f-f71bb9f05066.png)
![image](https://user-images.githubusercontent.com/44539789/58684360-9f732500-8395-11e9-823c-ee614e147d18.png)

**Comment by SaiSingamsetty** [comment]
> Hi @SaiSingamsetty - what happens when you log a `Verbose` event? I.e. does it show up at sinks? Thanks!

Actually there is no problem in using Verbose as it captures everything. But the issue is why it (minimumLevel) is not picking what I am configuring in JSON file. I might come across a situation where I have to log only Errors or Exceptions, at that time I cannot compromise with Verbose. So I am trying to figure out what is causing this issue. Hope I am clear. :)

**Comment by nblumhardt** [comment]
Thanks for the clarification @SaiSingamsetty . Have you tried capturing Serilog's `SelfLog` output?

Also, version 3.1.0 of _Serilog.Settings.Configuration_ was just released, and includes some better SelfLog diagnostics - may be worth a try, too.

**Comment by dimavs** [comment]
I've got the same issue. Serilog.Settings.Configuration (tried versions 3.0.1 and the same upgraded to 3.1.0)
MinimumLevel is always set to Verbose, irrespective to config settings

**Comment by nblumhardt** [comment]
Sounds like we might have a bug, here. If anyone has an opportunity to investigate/debug before one of us gets there, any clues/data would be much appreciated!

**Comment by nblumhardt** [comment]
Hi again;

I just tried to reproduce this here and thought I had it! Until I realised that my `appsettings.Development.json` file had an override for `MinimumLevel.Default` set to `Debug`. I think this might be based on an earlier sample we published somewhere.

After fixing the JSON configuration, I tested, re-tested, and triple-tested level control in version 3.0.1 and could not reproduce the issue.

If your problem isn't the same one @dimavs @SaiSingamsetty, can you please zip up (or gist) a complete CSPROJ + Program.cs that demonstrates the issue?

Best regards,
Nick

**Comment by dimavs** [comment]
@nblumhardt  I couldn't reproduce it on my Linux box with console application, I'll try to strip down my work project on Windows box tomorrow.

**Comment by dimavs** [comment]
After some investigation, I've found that it's a human error in my case :-)
Logging itself works as expected, it's just that Log.Logger._minimumLevel caused confusion for me. Log itsef got correct _minimumLevel

![image](https://user-images.githubusercontent.com/71602/60143243-aceac600-9800-11e9-893c-403c897b80b0.png)

**Comment by SaiSingamsetty** [comment]
Yes, same in my case. Logging works as expected, but the property _minimumLevel was confusion.
