### ISSUE TITLE
Microsoft.Extensions.Configuration.Json dependency

### ISSUE THREAD

**Issue by archerian** [serilog/serilog-settings-configuration#181]
Microsoft.Extensions.Configuration.Json is a required dependency for this feature, might be a good idea to add this to the documentation

**Comment by nblumhardt** [comment]
Hi! Thanks for the note. The package you mention is only required if JSON configuration is needed; this package supports the other _Microsoft.Extensions.Configuration.*_ providers, too, e.g. including environment variables.

I'll try cleaning up the README wording :+1:
