### ISSUE TITLE
retainedFileCountLimit default not 31

### ISSUE THREAD

**Issue by archerian** [serilog/serilog-settings-configuration#183]
The documentation says 'Old files will be cleaned up as per retainedFileCountLimit - the default is 31.'

But looks like this parameter has to be explicitly added with a value to get the feature, else the retention policy isn't applied.

**Comment by nblumhardt** [comment]
Hi Archerian,

I've tested this further and can't reproduce it. I'm using the latest versions of _Serilog.Sinks.File_ and _Serilog.Sinks.Configuration_, running on .NET Core 2.0.

Is there a chance you can boil your solution down into a minimal console app that reproduces the issue?

Best regards,
Nick

**Comment by skomis-mm** [comment]
Hi @archerian ,

Could not reproduce this too. If you still hit the issue try to update to the latest version. Otherwise, re-open the issue. Thanks
