### ISSUE TITLE
Can't use JSON event formatting with appsettings.json 

### ISSUE THREAD

**Issue by PedroS11** [serilog/serilog-settings-configuration#185]
I wanted to log in json files with .Net Core 2.2. However, it writes my logs in a non json format

Here is my appsettings.json file

```json
  "Serilog": {
    "MinimumLevel": "Fatal",
    "WriteTo": [
      {
        "Name": "Async",
        "Args": {
          "configure": [
            {
              "Name": "File",
              "Args": {
                "path": "..\\Logs\\log.json",
                "formatter": "Serilog.Formatting.Compact.CompactJsonFormatter, Serilog.Formatting.Compact",
                "rollingInterval": "Day",
                "retainedFileCountLimit": 5, 
                "fileSizeLimitBytes": 1073741824, 
                "rollOnFileSizeLimit": true, 
                "outputTemplate": "{Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz} [{Level}] {Message}{NewLine}{Exception}{NewLine}"
              }
            }
          ]
        }
      }
    ],
    "Properties": {
      "Application": "Common feature in WebApi demo"
    }
  },
```

I even tried to delete the _outputTemplate_ field but it always writes as
`2019-06-05 10:42:32.952 +01:00 [Fatal] {My data}`

**Comment by nblumhardt** [comment]
Hi Pedro,

The problem here is that `outputTemplate` and `formatter` are mutually-exclusive: only one or the other should be specified. Currently, when the configuration is ambiguous, the library will just choose one itself, which is `outputTemplate` in this case.

Removing the `outputTemplate` option will get this working.

HTH!

**Comment by PedroS11** [comment]
Even without it, it doesn't work, it keeps the same structure

**Comment by nblumhardt** [comment]
Thanks for the follow-up. Can you please include a minimal CSPROJ/Program.cs that reproduces the issue? I've been unsuccessful so far, and so we'll need this in order to make progress. Cheers!

**Comment by TroySchmidt** [comment]
Just a stab in the dark, but did you make sure to include `Serilog.Formatting.Compact` library as a dependency?

**Comment by skomis-mm** [comment]
Hi @PedroS11 ,

Just checked with your config, it works. If you still hit the issue, try to update to the latest versions of the packages. If it doesn't help, please re-open issue. Thanks
