### ISSUE TITLE
Configuring Serilog in Program.cs overrides default configuration behavior

### ISSUE THREAD

**Issue by LeonidasFettikus** [serilog/serilog-settings-configuration#186]
Hi guys,

I followed the example and configured Serilog like this:

```
public class Program
{
    public static int Main(string[] args)
    {
        var Configuration = new ConfigurationBuilder()
            .SetBasePath(Directory.GetCurrentDirectory())
            .AddJsonFile("appsettings.json")
            .Build();

        CreateLogger(Configuration);

        try
        {
            Log.Information("Starting host");
            CreateWebHostBuilder(args).Run();
            return 0;
        }
        catch (Exception ex)
        {
            Log.Fatal(ex, "Host terminated unexpectedly");
            return 1;
        }
        finally
        {
            Log.CloseAndFlush();
        }
    }

    public static IWebHost CreateWebHostBuilder(string[] args) =>
        WebHost.CreateDefaultBuilder(args)
            .UseStartup<Startup>()
            .UseSerilog()
            .Build();

    public static ILogger CreateLogger(IConfiguration Configuration) =>
        Log.Logger = new LoggerConfiguration()            
            .ReadFrom.Configuration(Configuration)
            .CreateLogger();
}
```

The logging itself works. However, this overrides various default configuration behaviors. For example, if I store my connection strings, some email addresses, etc. in secrets.json, it will not work anymore unless I implement the behavior myself in my `Configuration` initialization. For dev purposes, I use secrets.json and for production I use azure app settings. This would mean that I need to configure these two config sources myself, provided this entails no additional errors down the road.

Is there some way in doing this without breaking the whole configuration behavior? I just need to have dependency injection with my settings coming from appsettings.json or appsettings.Development.json.

**Comment by mebymyself** [comment]
@LeonidasFettikus , I am facing similar problem.  how did you solve this?
