### ISSUE TITLE
Specific level for each writer

### ISSUE THREAD

**Issue by fleed** [serilog/serilog-settings-configuration#19]
Is it possible to specify a different level of logging for each writer?

Example:

- `File`: **Debug**
- `LiterateConsole`: **Information**

**Comment by merbla** [comment]
Hey @fleed,

You can use the params for the relative sink configuration in your `appsettings.json`.

If you look at the [example](https://github.com/serilog/serilog-settings-configuration/tree/dev/sample/Sample) and add the `restrictedToMinimumLevel` setting.

You will get this output 

```bash
[17:03:09 Microsoft [WRN] Hello, world!
```

This can be done at the logger or sink level.

Short version

```
"WriteTo": [
      {
        "Name": "LiterateConsole",
        "Args": {
          "restrictedToMinimumLevel":"Warning",
....

```

Full version from example
```
{
  "Serilog": {
    "Using":  ["Serilog.Sinks.Literate"],
    "MinimumLevel": {
      "Default": "Debug",
      "Override": {
        "Microsoft": "Warning",
        "MyApp.Something.Tricky": "Verbose"
      }
    },
    "WriteTo": [
      {
        "Name": "LiterateConsole",
        "Args": {
          "restrictedToMinimumLevel":"Information",
          "outputTemplate": "[{Timestamp:HH:mm:ss} {SourceContext} [{Level}] {Message}{NewLine}{Exception}"
        } 
      },
      {        
        "Name": "File",
        "Args": {
          "restrictedToMinimumLevel":"Debug",
          "path": "serilog-configuration-sample.txt",
          "outputTemplate": "{Timestamp:o} [{Level,3:u}] ({Application}/{MachineName}/{ThreadId}) {Message}{NewLine}{Exception}"
        }
      }
    ],
    "Enrich": ["FromLogContext", "WithMachineName", "WithThreadId"],
    "Properties": {
      "Application": "Sample"
    }
  }
}
```

**Comment by fleed** [comment]
Thanks @merbla 
I didn't remember the name of the `restrictedToMinimumLevel` parameter, I think it would be good to add it to the example you've mentioned (that's the first place where I've searched it)

**Comment by phenry9999** [comment]
How do you do this same thing for the app.config?

**Comment by tsimbalar** [comment]
@phenry9999 here is an example, take from https://github.com/tsimbalar/serilog-settings-comparison/blob/master/docs/README.md#sinks---restrictedtominimumlevel

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <appSettings>
    <add key="serilog:using:TestDummies" value="TestDummies" />
    <add key="serilog:write-to:Dummy.restrictedToMinimumLevel" value="Error" />
  </appSettings>
</configuration>
```

**Comment by phenry9999** [comment]
Thank you Tsimbalar. I tried what was listed there, unfortunately I don't see any impact. :<
I have added these two lines to my app.config
<add key="serilog:write-to:RollingFile.restrictedToMinimumLevel" value="Debug" />
<add key="serilog:write-to:Console.restrictedToMinimumLevel" value="Information" />

Expecting to see my Log.Debug in the log file (which normally shows stuff) but now I'm only seeing information in both the log file and the console. Is there anything else I can try?

**Comment by phenry9999** [comment]
I did try this out again and this time I got it to work. The trick in my case was, I had to first add 
<add key="serilog:minimum-level" value="Debug"/>
Then I had to delete the existing log. Once I did that, I got the separate logging.

I believe the first addition tells Serilog "what" to listen for, and if it's passed that (Serilog is interested), then it passes it off to the sinks to see if they are interested in logging. I'm not quite sure what the connecting is with the existence of the previous log file has though?

**Comment by tsimbalar** [comment]
Yes, there is a "global" minimum level that says, no matter what, I'll ignore vents under level X. By default it is "Information", which means Debug events are ignored by default, event if some sinks accept them.

You can read more about it in the doc : https://github.com/serilog/serilog/wiki/Configuration-Basics#minimum-level
