### ISSUE TITLE
NU1605 compile error:  Detected package downgrade: Serilog.Settings.Configuration 3.1.0 -> Microsoft.Extensions.DependencyModel 2.0.4 

### ISSUE THREAD

**Issue by icearn** [serilog/serilog-settings-configuration#196]
Hi guys,

I am trying to compile my project under .net standard 2.0 with serilog setting configuration 3.1.0 and I got these errors:

 warning NU1605: Detected package downgrade: System.Collections from 4.3.0 to 4.0.11. Reference the package directly from the project to select a different version.
warning NU1605: Detected package downgrade: System.IO.FileSystem.Primitives from 4.3.0 to 4.0.1. Reference the package directly from the project to select a different version.

warning NU1605: 
 Serilog.Settings.Configuration 3.1.0 -> Microsoft.Extensions.DependencyModel 2.0.4 -> Microsoft.DotNet.PlatformAbstractions 2.0.4 -> System.IO.FileSystem 4.0.1 -> runtime.win.System.IO.FileSystem 4.3.0 -> System.Runtime.Handles (>= 4.3.0)

I've set ignoring NU1605 error in the project so it can temporarily build and release. Just wondering do we have a plan to upgrade dependencies? I assume this is a dependency upgrade issue - please correct me if I was wrong.

Thanks a lot

Icearn

**Comment by ckadluba** [comment]
I also got this error in a OutputType EXE project targeting .NET Core 3.1. There I indirectly reference Serilog.Settings.Configuration via some .NET Standard 2.1 assemblies. The following happens when I execute dotnet publish.

```
Workflow.CamundaValidator.csproj : error NU1605: Detected package downgrade: System.Collections from 4.3.0 to 4.0.11. Reference the package directly from the project to select a different version.
Workflow.CamundaValidator.csproj : error NU1605:  Workflow.CamundaValidator -> Workflow.CamundaHelpers 1.2.0 -> Logging.Web 2.1.1 -> Logging 2.3.4 -> Serilog.Settings.Configuration 3.1.0 -> Microsoft.Extensions.DependencyModel 2.0.4 -> Microsoft.DotNet.PlatformAbstractions 2.0.4 -> System.IO.FileSystem 4.0.1 -> runtime.win.System.IO.FileSystem 4.3.0 -> System.Collections (>= 4.3.0)
Workflow.CamundaValidator.csproj : error NU1605:  Workflow.CamundaValidator -> Workflow.CamundaHelpers 1.2.0 -> Logging.Web 2.1.1 -> Logging 2.3.4 -> Serilog.Settings.Configuration 3.1.0 -> Microsoft.Extensions.DependencyModel 2.0.4 -> Microsoft.DotNet.PlatformAbstractions 2.0.4 -> System.Collections (>= 4.0.11)
```

Could only get rid of the error by directly referencing System.Collections 4.3.0 which is of course only a workaround but not a real fix.
