### ISSUE TITLE
Serilog.Settings.Configuration 3.1.0 transitivly brings Newtonsoft.Json 9.0.1

### ISSUE THREAD

**Issue by GeneralGDA** [serilog/serilog-settings-configuration#197]
Serilog.Settings.Configuration transitively brings (via Microsoft.Extensions.DependencyModel 2.0.4) Newtonsoft.Json 9.0.1. And it is painful to use both Serilog.Settings.Configuration and new versions of Newtonsoft.Json in a single project (it is impossible, actually). And brings constant troubles in multi-project solutions.

**Comment by nblumhardt** [comment]
Thanks for the note. Some alternative dependencies/targeting that avoids this seems like it would be worthwhile 👍
