### ISSUE TITLE
Provided example of new ConfigurationBuilder() throws an exception

### ISSUE THREAD

**Issue by pfaustinopt** [serilog/serilog-settings-configuration#198]
If I copy this code to my project `var configuration = new ConfigurationBuilder()            .AddJsonFile("appsettings.json").Build();` and run it, I get the following exception:

`Exception thrown: 'System.IO.FileNotFoundException' in Microsoft.Extensions.Configuration.FileExtensions.dll`

I can solve this problem either by setting `Copy to Output Directory` to `Copy Always` on `appsettings.json` or by adding this line of code `.SetBasePath(Directory.GetCurrentDirectory())` when creating the `ConfigurationBuilder`.

Am I supposed to apply this workaround or am I doing something wrong?

**Comment by nblumhardt** [comment]
Hi! There's no Serilog code involved in this, so I am not sure we're best placed to answer, but calling `.SetBasePath(Directory.CurrentDirectory)` seems reasonable to me (I believe this is what the framework does by default).

**Comment by pfaustinopt** [comment]
> There's no Serilog code involved

Thats correct, I was just posting this here because I was configuring Serilog based on the README instructions.

I'll use `.SetBasePath(Directory.CurrentDirectory)` then. Thank you!

**Comment by nblumhardt** [comment]
Great, thanks! 👍
