### ISSUE TITLE
AuditTo.Logger not supported in Json configuration

### ISSUE THREAD

**Issue by leejeffr** [serilog/serilog-settings-configuration#199]
Please support Json configuration for the "AuditTo.Logger". I happened to be using the TestCorrelator sink but feel free to swap that out. 

`"AuditTo:TestCorrelatorSubLogger": 
    {
      "Name": "Logger",
      "Args": {
        "configureLogger": {
          "Filter": [
            {
              "Name": "ByIncludingOnly",
              "Args": {
                "expression": "A = 'ABC'"
              }
            }
          ],
          "AuditTo": [
            {
              "Name": "TestCorrelator"
            }
          ]
        }
      }
    }`

2019-10-22T16:43:55.1913422Z Unable to find a method called Logger. Candidate methods are:
Serilog.LoggerConfiguration File(Serilog.Configuration.LoggerAuditSinkConfiguration, System.String, Serilog.Events.LogEventLevel, System.String, System.IFormatProvider, Serilog.Core.LoggingLevelSwitch)
Serilog.LoggerConfiguration File(Serilog.Configuration.LoggerAuditSinkConfiguration, Serilog.Formatting.ITextFormatter, System.String, Serilog.Events.LogEventLevel, Serilog.Core.LoggingLevelSwitch)
Serilog.LoggerConfiguration File(Serilog.Configuration.LoggerAuditSinkConfiguration, System.String, Serilog.Events.LogEventLevel, System.String, System.IFormatProvider, Serilog.Core.LoggingLevelSwitch, System.Text.Encoding, Serilog.Sinks.File.FileLifecycleHooks)
Serilog.LoggerConfiguration File(Serilog.Configuration.LoggerAuditSinkConfiguration, Serilog.Formatting.ITextFormatter, System.String, Serilog.Events.LogEventLevel, Serilog.Core.LoggingLevelSwitch, System.Text.Encoding, Serilog.Sinks.File.FileLifecycleHooks)
Serilog.LoggerConfiguration TestCorrelator(Serilog.Configuration.LoggerAuditSinkConfiguration, Serilog.Events.LogEventLevel, Serilog.Core.LoggingLevelSwitch)
Serilog.LoggerConfiguration Sink(Serilog.Configuration.LoggerAuditSinkConfiguration, Serilog.Core.ILogEventSink, Serilog.Events.LogEventLevel, Serilog.Core.LoggingLevelSwitch)

**Comment by nblumhardt** [comment]
Thanks for the note - we should be able to support this 👍
