### ISSUE TITLE
Support MSBuild (non-project.json) projects

### ISSUE THREAD

**Issue by OzieGamma** [serilog/serilog-settings-configuration#20]
File: https://github.com/serilog/serilog-settings-configuration/blob/dev/src/Serilog.Settings.Configuration/ConfigurationLoggerConfigurationExtensions.cs

Source:
```csharp
context = DependencyContext.Default;
if (context == null)
  throw new InvalidOperationException("Add `\"preserveCompilationContext\": true` to `\"buildOptions\"` for support on .NET 4.x.");
```

When using this lib as part of a set-by-step upgrade from .NET 3.5 WinForms to .NET Core ASP.NET MVC I get the above exception to trigger. Any idea how to avoid it ?

**Comment by nblumhardt** [comment]
Hi @OzieGamma - can you please include your `buildOptions` node from project.json? Thanks!

**Comment by OzieGamma** [comment]
I am not building with .NET Core ...

**Comment by nblumhardt** [comment]
Thanks for the update. It looks like the required `.deps.json` file is only generated by the `dotnet` tooling (project.json), not MSBuild, so for now it seems this library is only going to work with that project system.

I think with conditional compilation it should be possible to break the dependency this library has on `DependencyContext`, using `AppDomain` instead on the full framework. Marking this issue as up-for-grabs. Thanks!
