### ISSUE TITLE
How to configure from JSON, but then get a reference to the switch?

### ISSUE THREAD

**Issue by dazinator** [serilog/serilog-settings-configuration#206]
I'd like to use the json configuration to configure the seq sink. However I need access to the switch in code, because I want to allow this to be changed at runtime in code. How should I go about that?

**Comment by dazinator** [comment]
I managed to work around this in the end, but I had to bypass serilog's switch.
I wrapped the `SerilogLoggerProvider` with my own LoggerProvider - with my own LogLevel switch. My top level LoggerProvider only forwards events to the SerilogLoggerProvider if the log event meets the log level dictated by its switch. In essence it's pretty much putting my own gate in front of the SerilogLoggerProvider. I could then just configure the serilog logger to be minimum level verbose, and use config to configure it as I needed.

**Comment by mrxrsd** [comment]
I was trying to do this just right now. I've tought it will be possible like we pass formatters to json using static variables. 

It will be a great feature!

``` json
{
    "Serilog": {
        "LevelSwitches": { 
           "$controlSwitch": "Verbose",
           "exposeAt": "Sample.Switchlevel, Sample"
        },
        "WriteTo": [
            {
                "Name": "Seq",
                "Args": {
                    "serverUrl": "http://localhost:5341",
                    "apiKey": "yeEZyL3SMcxEKUijBjN",
                    "controlLevelSwitch": "$controlSwitch"
                }
            }
        ]
    }
}
```

**Comment by dazinator** [comment]
@mrxrsd your proposal couples the json a bit too tightly to code structure for my level of comfort. Id prefer just naming the switch in the json, and then serilog exposing some dictionary at runtime to retrieve named switches. That way, refactoring code wouldn't break anything.

**Comment by tsimbalar** [comment]
FYI, you should be able to use the "hack" proposed in this issue until there's an official way to do it : 

https://github.com/serilog/serilog-settings-appsettings/issues/24#issuecomment-379396610

**Comment by skomis-mm** [comment]
Would be great to add support for this . Without upstream support we could solve it with adding additional parameter or new overloads to `ReadFrom.Configuration` with switch collector type:
```csharp
var switchCollector = new LoggerSwitchCollector();

var logger = new LoggerConfiguration()
    .ReadFrom.Configuration(configuration, switchCollector)
    .CreateLogger();

var controlSwitch = switchCollector.GetLevelSwitch("controlSwitch");
```

**Comment by tsimbalar** [comment]
By touching the core `Serilog`library, we could also somehow expose the underlying `LevelOverrideMap` available in a `Logger`but this seems like leaking internals a bit too much... 

@skomis-mm  I like your suggestion, and wonder, if we could/should even make it a more generic way to "introspect" on the results of configuring through the `Configuration`Settings Provider.

So for instance : 

```cs

var logger = new LoggerConfiguration()
    .ReadFrom.Configuration(configuration, out var loadedConfiguration)
    .CreateLogger();

var switch = loadedConfiguration.GetLevelSwith("controlSwitch");
```

i.e. `ReadFrom.Configuration`takes a second optional argument that returns some sort of object that contains information about the configuration that we loaded. 

For now, it would just allow to look up switches, but we could extend it later to have, possibly, diagnostics about the process of loading the configuration or other useful information.

**Comment by skomis-mm** [comment]
@tsimbalar some generic type was in my mind too. 👍 

`out` modifier seems good addition. No need to import additional namespace for the type in case of inline initialization .

**Comment by gowon** [comment]
I wanted to share my solution for this problem when I hit it a few months ago:

- Create a dummy sink that takes the switch and a label
- The LoggerSinkConfiguration extension method adds the dynamically generated switches and labels as key-value-pairs to a singleton collection that can be refererenced outside of the logger.
- (optional) Add an extension to attach the singleton collection to the generic host DI

I wrapped it into a package here: <https://github.com/gowon/Serilog.Sinks.DynamicSwitch>. It feels a bit hacky, and I wish I could make it less verbose on the json side, but it gets the job done until there's some first-class interface for reaching those switches.

**Comment by 0xced** [comment]
I just submitted #347 to address this issue. I am looking forward to your feedback over there.

**Comment by mrxrsd** [comment]
I've been worked in a solution using reflection, still a WIP but is already usable and publish. 

https://github.com/mrxrsd/dynamic-serilog-switch
