### ISSUE TITLE
Multiple sinks ignores first sink's WriteTo config

### ISSUE THREAD

**Issue by Tom-Dunstan** [serilog/serilog-settings-configuration#208]
I'm not sure if this is a bug or if it's my mistake, as I'm new to Serilog

I wanted to have Serilog log to two sinks for each write to the log, the console and a mongoDB database. What I found was that only one was working, always the last one defined. 

```json
{
  "Serilog": {
    "MinimumLevel": {
      "Default": "Debug",
      "Override": {
        "Microsoft": "Warning",
        "System": "Warning"
      }
    },
    "WriteTo": [
      {},
      {
        "Name": "Console",
        "Args": {
          "theme": "Serilog.Sinks.SystemConsole.Themes.AnsiConsoleTheme::Code, Serilog.Sinks.Console",
          "outputTemplate": "[{Timestamp:HH:mm:ss.fff} {Application} {Level:u3}][{RequestId}] {SourceContext}: {Message:lj}{NewLine}{Exception}"
        }
      },
      {
        "Name": "MongoDBCapped",
        "Args": {
          "databaseUrl": "mongodb://myurl:27017/mydb",
          "collectionName": "log",
          "cappedMaxSizeMb": "50",
          "cappedMaxDocuments": "1000"
        }
      }
    ],
    "Enrich": [ "FromLogContext", "WithDemystifiedStackTraces" ]
  }
}
```

At first I thought that the second sink was replacing the first and so only one was configured

**Comment by skomis-mm** [comment]
Hi @Tom-Dunstan ,

Sorry for a late reply. Your config looks totally fine to me. Do you still hit the issue?

**Comment by Tom-Dunstan** [comment]
@skomis-mm, Sorry I thought I'd closed this and replied. It turned out my transform for the appsettings.json file was interfering with it. I've fixed it now
