### ISSUE TITLE
Think the readme documentation for .NET 4.8 might be wrong

### ISSUE THREAD

**Issue by KiransHub** [serilog/serilog-settings-configuration#210]
Hey, I have an application in .NET 4.5. 

The read me talks about a project.json but my project file is xml based.
I've got a web.config file and again that is XML not Json.

I may be miss understanding things here but I seem to be remember that the way to do this was different in .NET 4.5

**Comment by KiransHub** [comment]
Update: 

I found this https://github.com/serilog/serilog-settings-appsettings

Perhaps this should be mentioned in the docs?

**Comment by nblumhardt** [comment]
Thanks for the suggestion, will keep it in mind. Glad you were able to find what you need!
