### ISSUE TITLE
Question: Conditional Filters per WriteTo using Json

### ISSUE THREAD

**Issue by Danny2036** [serilog/serilog-settings-configuration#211]
I am trying to set my serilog up, so that when logging occurs only specific logs will be written to a log file. I imagine that this could work logging to different sinks as well, which I intend to try. For now, I am looking at logging to different files. In my configuration I have a property that comes from an enricher. When that property is set to true I want the log to be written to `Path2`. I want all logs to go to `Path1`. I imagine this would have a global `WriteTo` that would point to `Path1\\log` and a sub logger that has a filter that would point to `Path2\\log`. 

Currently, I am able to write to two different locations. I am also able to set a global filter that will filter everything for any log file that is created. My issue is that I am unable to write to two log files, but only filter one of the files.

The first snippet has code writes to two files and has a filter that applies to both
```
{
  "Serilog": {
    "Using": [
      "Serilog.Sinks.File",
      "Serilog.Filters.Expressions"
    ],
    "MinimumLevel": {
      "Default": "Information"
    },
    "Filter": [
      {
        "Name": "ByIncludingOnly",
        "Args": {
          "expression": "Path2 = true"
        }
      }
    ],
    "WriteTo": [
      {
        "Name": "File",
        "Args": {
          "formatter": "Serilog.Formatting.Json.JsonFormatter, Serilog",
          "path": "C:[Path2]\\log.json"
        }
      },
      {
        "Name": "File",
        "Args": {
          "formatter": "Serilog.Formatting.Json.JsonFormatter, Serilog",
          "path": "C:[Path2]\\log.json",
        }
      }
    ],
    "Enrich": [
      "Path2"
    ]
  }
}
```

My second snippet has what I am attempting to do by only filtering a single output
```
{
  "Serilog": {
    "Using": [
      "Serilog.Sinks.File"
    ],
    "MinimumLevel": {
      "Default": "Information"
      }
    },
    "WriteTo": [
      {
        "Name": "File",
        "Args": {
          "formatter": "Serilog.Formatting.Json.JsonFormatter, Serilog",
          "path": "C:[Path1]\\log.json"
        }
      },
      {
        "Name": "File",
        "Args": {
          "formatter": "Serilog.Formatting.Json.JsonFormatter, Serilog",
          "path": "C:[Path2]\\log.json"
        },
        "Filter": [
          {
            "Name": "ByIncludingOnly",
            "Args": {
              "expression": "Path2 = 'true'"
            }
          }
        ]
      }
    ],
    "Enrich": [
      "Path2"
    ]
  }
}
```
I have a third snippet which I attempted based off of [documentation ](https://github.com/tsimbalar/serilog-settings-comparison/blob/master/docs/README.md)I found for using json config. But following that documentation I will unable to actually right to a file, but I thought it might be helpful to include as well.
```
{
  "Serilog": {
    "Using": [
      "Serilog.Sinks.File",
      "Serilog.Filters.Expressions"
    ],
    "MinimumLevel": {
      "Default": "Information"
      }
    },
    "WriteTo:Path1": {
      "Name": "Logger",
      "Args": {
        "configureLogger": {
          "WriteTo": {
            "Args": {
              "formatter": "Serilog.Formatting.Json.JsonFormatter, Serilog",
              "path": "C:[Path1]\\log.json"
            }
          }
        }
      }
    },
    "WriteTo:Path2": {
      "Name": "Logger",
      "Args": {
        "configureLogger": {
          "Filter": [
            {
              "Name": "ByIncludingOnly",
              "Args": {
                "expression": "Path2 = true"
              }
            }
          ],
          "WriteTo": {
            "Args": {
              "formatter": "Serilog.Formatting.Json.JsonFormatter, Serilog",
              "path": "C:[Path2]\\log.json"
            }
          }
        }
      }
    }
  }
```

 Any thoughts or suggestions are much appreciated.

**Comment by skomis-mm** [comment]
Hi @Danny2036 ,

The third attempt is the closest. Here the correct setup:

```json
{
  "Serilog": {
   "Using": [
      "Serilog.Sinks.File",
      "Serilog.Filters.Expressions"
    ],
    "MinimumLevel": {
      "Default": "Information"
    },
    "WriteTo:Path1": {
      "Name": "File",
      "Args": {
        "formatter": "Serilog.Formatting.Json.JsonFormatter, Serilog",
        "path": "C:[Path1]\\log.json"
      }
    },
    "WriteTo:Path2": {
      "Name": "Logger",
      "Args": {
        "configureLogger": {
          "Filter": [
            {
              "Name": "ByIncludingOnly",
              "Args": {
                "expression": "Path2 = 'True'"
              }
            }
          ],
          "WriteTo:File": {
            "Name": "File",
            "Args": {
              "formatter": "Serilog.Formatting.Json.JsonFormatter, Serilog",
              "path": "C:[Path2]\\log.json"
            }
          }
        }
      }
    },
    "Properties": {
      "Path2": true
    }
  }
}
```

**Comment by Danny2036** [comment]
Hey @skomis-mm,
Thanks for getting back to me. I appreciate it. I have tried the config you posted and I am still getting the same result of only writing logs to Path1. Nothing is appearing in Path2. If I move the filter to the top level the filter still works, but no logs still get written to Path2. 
The order of the json elements makes sense to me, so I could imagine the filter is working, but the sublogger is not. Do you know what the minimum version for serilog is to be able to use subloggers? 
Here is also my current working version based on what you sent me. 
```
{
  "Serilog": {
    "Using": [
      "Serilog.Sinks.File",
      "Serilog.Filters.Expressions"
    ],
    "MinimumLevel": {
      "Default": "Information"
    },
    "WriteTo:Path1": {
      "Name": "File",
      "Args": {
        "formatter": "Serilog.Formatting.Json.JsonFormatter, Serilog",
        "path": "[Path1]\\log.json"
	"rollingInterval": "Day"
      }
    },
    "WriteTo:Path2": {
      "Name": "Logger",
      "Args": {
        "configureLogger": {
          "Filter": [
            {
              "Name": "ByIncludingOnly",
              "Args": {
                "expression": "Path2Status = true"
              }
            }
          ],
          "WriteTo:File": {
            "Name": "File",
            "Args": {
              "formatter": "Serilog.Formatting.Json.JsonFormatter, Serilog",
              "path": "[Path2]\\log.json",
	      "rollingInterval": "Day"
            }
          }
        }
      }
    }
  }
}
```
One big difference is the property was moved to code configuration instead of this file. There is also a rolling interval for logging. Let me know if you have any other ideas. Thank you!

**Comment by skomis-mm** [comment]
Hi @Danny2036 ,

Try the latest version of `Serilog.Settings.Configuration` (3.1.0). Also values in expression should be quoted:
```json
"expression": "Path2Status = 'True'"
```

**Comment by Danny2036** [comment]
Hey @skomis-mm,
I will try switching versions and let you know if that works for me! 

Also, it could be the version I am on, but the global filter does work without the single quotes interestingly enough. But if that is the more correct way then I will change that as well.
Thanks!

**Comment by Danny2036** [comment]
Hey @skomis-mm,
From what I saw about switching to 3.1.0 require .Net Core and I am still using .NET Framework. So, unless I am mistaken this does not look like I will be able to filter this way if that is the case.

**Comment by skomis-mm** [comment]
Hi @Danny2036 ,

This package supports .NET Framework (v4.5.1+ and Microsoft.Extensions.Configuration v.1.1.x, 4.6.1+ and Microsoft.Extensions.Configuration v2, v3)

**Comment by Danny2036** [comment]
Hey @skomis-mm,
Thank you so much. Switching to 3.1.0. My filter is now working properly the way I want. Now, I just need to have to look at filtering on specific sinks as well. But I have a couple of resources I am going to reference that I think might get me the solutions I need. Again, thanks a lot!
