### ISSUE TITLE
Usage of configuration settings of a json file into Serilog in Azure Function V3

### ISSUE THREAD

**Issue by crasDev** [serilog/serilog-settings-configuration#217]
I am trying to add Serilog to a V3 Azure Function, that I made with success but now I want to bring configuration settings for Serilog from the json.file but in that case, I´m failing.

I have also set the Azure Function that it already consumes that json file to startup alot of DI services ( like repositories, obtain queue names, etc ) so I know that the Json file is correctly used to a IConfiguration, but when I use the ReadFrom.Configuration(config) inside the Startup.cs , inside the method public override void Configure(IFunctionsHostBuilder builder) and it does not get the settings that I desire to extract from the json file.

I have installed the following packages:
Serilog.AspNetCore V 3.2.0
Serilog.Settings.Configuration V3.1.0
Serilog.Sinks.Consolle V3.1.1
Serilog.Sinks.File V4.1.0

The settings I want to extract from the json file are (and please consider that I have those exact same settings on a .Net Core 2.2 web api and it works really fine):
"Serilog": {
    "Using": [ "Serilog.Sinks.Console", "Serilog.Sinks.File" ],
    "MinimumLevel": {
      "Default": "Trace",
      "Override": {
        "Microsoft": "Warning",
        "System": "Debug"
      }
    },
    "Enrich": [ "FromLogContext" ],
    "WriteTo": [
      {
        "Name": "Console",
        "Args": {
          "outputTemplate": "===> {Timestamp:HH:mm:ss.fff zzz} [{Level}] {Message}{NewLine}{Exception}"
        }
      },
      {
        "Name": "File",
        "Args": {
          "path": "D:\\Logs\\xxx\\xxx-WebApi.log",
          "rollingInterval": "Day",
          "outputTemplate": "===> {Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz} [{Level}] {Message}{NewLine}{Exception}",
          "restrictedToMinimumLevel": "Information"
        }
      }
    ]
  }

**Comment by vpaulino** [comment]
On Asp.net core we are Adding the UseSerilog method on the Program.cs when setting up the host like this: 
 
`WebHost.CreateDefaultBuilder(args).UseSerilog((ctx, config) => { config.ReadFrom.Configuration(ctx.Configuration); })
`
 this method is an extension method of IWebHostBuilder.  But this error is nothing related to the HostBuilder because configuration responsability belongs to Configuration extensions namespace. 
See this if it helps: https://stackoverflow.com/questions/55023824/azure-function-failing-to-initialise-serilog-sink-when-using-appsettings-json#55067729

**Comment by skomis-mm** [comment]
Hi @crasDev , according to the [docs](https://docs.microsoft.com/en-us/azure/azure-functions/functions-app-settings#azurefunctionsjobhost__) you need to use prefix `AzureFunctionsJobHost` for a custom section in `host.json`. So for a default `Serilog` section your setup should look like:
```csharp
var logger = new LoggerConfiguration()
   .ReadFrom.Configuration(config, "AzureFunctionsJobHost:Serilog")
   .CreateLogger();
```
