### ISSUE TITLE
Add support for 'internal' types in custom method discovery?

### ISSUE THREAD

**Issue by julealgon** [serilog/serilog-settings-configuration#229]
As part of https://github.com/serilog/serilog-sinks-map/issues/22, I ended up creating a custom extension method for my particular case, then configuring my appsettings to use it, adding the `Using` node in the json pointing to my assembly.

However, it only seems to work when the method is exposed in a `public` class. Trying to change it to `internal` and adding a `InternalsVisibleTo` attribute in my project targeting `Serilog.Settings.Configuration` didn't work at all: my method was just ignored.

I'd prefer keeping my method `internal` as I don't want anyone else from outside calling it (it is specific to this particular project).

Can this scenario be supported?

**Comment by nCubed** [comment]
Have you tried exposing the assembly to the `Serilog` assembly?

```csharp
[assembly: InternalsVisibleTo("Serilog")]
// may also need to expose to configuration as well
[assembly: InternalsVisibleTo("Serilog.Settings.Configuration")]
```

HTH's
