### ISSUE TITLE
Destructuring seems doesn't work for Azure Function V3

### ISSUE THREAD

**Issue by Ted-chiptech** [serilog/serilog-settings-configuration#230]
When I tried to destructing a object and log it to application insight, it doesn't seems work in Azure Function.
Strange part is it can destructing a object if I don't use the azure function configuration example from this repo's home page.

Doesn't work: if I setup the function by following the home page example, it doesn't destructing object.
![image](https://user-images.githubusercontent.com/64759040/90088463-1f0acb00-dd73-11ea-9aa9-a0bd93f0aa2b.png)
OR
```
services.Configure<IConfiguration>(ic =>
                {
                    services.AddLogging(o =>
                    {
                        var functionDependencyContext = DependencyContext.Load(typeof(Startup).Assembly);
                        var logger = new LoggerConfiguration()
                            .ReadFrom.Configuration(ic, "AzureFunctionsJobHost:Serilog", functionDependencyContext)
                            .Enrich.FromLogContext()
                            .WriteTo.ApplicationInsights(TelemetryConverter.Traces)
                            .CreateLogger();
                        o.ClearProviders().AddSerilog(logger, true);
                    });
                });
```

![image](https://user-images.githubusercontent.com/64759040/90088253-9d1aa200-dd72-11ea-86d0-b3c0317e407d.png)

It works if I call AddSerilog in the code, but I lost the ability to access the configuration in azure function.
```
services.AddLogging(o =>
                {
                    // read from config
                    var logger = new LoggerConfiguration()
                        //.ReadFrom.Configuration(hostConfig, "AzureFunctionsJobHost:Serilog", functionDependencyContext)
                        .Enrich.FromLogContext()
                        .WriteTo.ApplicationInsights(TelemetryConverter.Traces)
                        .CreateLogger();
                    o.ClearProviders().AddSerilog(logger, dispose: true);
                });
```
![image](https://user-images.githubusercontent.com/64759040/90088915-3f875500-dd74-11ea-8a9a-457efead84d3.png)

Thanks for your help!

**Comment by RizwanSharp** [comment]
Hello, 

I am facing the same issue. Were you able to find a solution to it?

Thanks in advance.
