### ISSUE TITLE
MinimumLevel gets ignored in environemnt specific appsettings.json if it has different structure

### ISSUE THREAD

**Issue by lordgog** [serilog/serilog-settings-configuration#232]
**Description**
Given the following settings:
appsettings.json
```
"Serilog": {
  "MinimumLevel": "Error"
}
```

appsettings.Development.json
```
"Serilog: {
  "MinimumLevel: {
    "Default": "Debug",
    "Override": {
      "Microsoft": "Warning"
    }
  }
}
```

The development configuration is ignored when the application runs in debug mode. Instead, MinimumLevel is set to Error.

**Comment by nblumhardt** [comment]
Thanks for the note; this is a result of how overrides in _Microsoft.Extensions.Configuration_ work. You'd need to change appsettings.json to:

```json
"Serilog": {
  "MinimumLevel": {
    "Default": "Error"
  }
}
```

in order for this to work.
