### ISSUE TITLE
[Question] - Is there a way to restrict max level on settings with minimum level?

### ISSUE THREAD

**Issue by Ryujose** [serilog/serilog-settings-configuration#236]
**Problem**

We need to separate in three files debug, information and error. But we don't see how we can do this and if it's possible.

For now our configuration is like this on our settings.json, but on debug we see debug and the upper levels and in the rest happens the same.

![image](https://user-images.githubusercontent.com/11687567/93132744-90100c00-f6ac-11ea-89b4-5b4732a252c6.png)

Is there some configuration to do these? Or what is the best practice you recommend? We need to send it like this with filebeat.

**Comment by skomis-mm** [comment]
Hi @Ryujose , sorry for a slow response. 

Check the available options [here](https://github.com/serilog/serilog-settings-configuration/issues/216).

**Comment by Ryujose** [comment]
Hi @skomis-mm we've seen that the expression part with `@level` have changed to `@l` on the assembly of https://github.com/serilog/serilog-expressions

For example it will be like `"expression": "@l in ['Verbose', 'Debug']",` instead of `@level in ['Verbose', 'Debug']",`

Maybe it will help you or somebody else on the future with these info!

Regards.
