### ISSUE TITLE
Specifying Override stops logging altogether

### ISSUE THREAD

**Issue by Thaoden** [serilog/serilog-settings-configuration#24]
I have the following Serilog configuration:

    {
      "Serilog": {
        "Using": [ "Serilog.Sinks.Literate", "Serilog.Sinks.Seq" ],
        "MinimumLevel": {
          "Default": "Information",
        //  "Override": {
        //    "Microsoft": "Warning",
        //    "System": "Debug"
        //  },
          "Enrich": [ "FromLogContext", "WithMachineName", "WithThreadId" ],
          "WriteTo": [
            {
              "Name": "LiterateConsole"
            },
            {
              "Name": "Seq",
              "Args": { "serverUrl": "http://localhost:5341" }
            }
          ]
        }
      }
    }

However, when I comment in the `Override`-section, the logging stops altogether and no output is generated on the console nor in Seq. Any hints on what I did wrong?

**Comment by skomis-mm** [comment]
@Thaoden , I believe it needs one more uncommented bracket after the last comment line: `}, "Enrich":` because they looks like in `MinimumLevel` section. Is that the case?

**Comment by Thaoden** [comment]
@skomis-mm Yes, it seems I've forgotten an brace *d'oh. 
Thanks!
