### ISSUE TITLE
%userprofile% does not get resolved

### ISSUE THREAD

**Issue by TehGM** [serilog/serilog-settings-configuration#246]
I am trying to configure appsettings.json to log to Documents folder, independent on user's name.

```json
// ...
"WriteTo": [
  {
    "Name": "File",
    "Args": {
      "path": "%userprofile%/Documents/logs/log.log"
    }
  }
]
// ...
```
Unfortunately, no log file is created.

When I try to use `%localappdata%` instead of `%userprofile%`, the log file gets created as expected. This rules out environment variables not being supported.  
It also works correctly when I specify full path to Documents folder, either programmatically or as raw JSON value. This rules out permissions issue.

**Package version tested**: 3.1.0

**Comment by sungam3r** [comment]
See https://github.com/serilog/serilog-settings-configuration/blob/dev/src/Serilog.Settings.Configuration/Settings/Configuration/StringArgumentValue.cs#L31 . Your example works for me on Windows:
![изображение](https://user-images.githubusercontent.com/21261007/103172514-2683ca00-4865-11eb-8480-76236c7217c8.png)

**Comment by skomis-mm** [comment]
Hi @TehGM ,

Environment variables are expanded on startup. I couldn't reproduce with sample project (probably, some sort of permission issue)
Please, re-open if it still actual.
