### ISSUE TITLE
Use of local.settings.json in Azure Functions with serilog

### ISSUE THREAD

**Issue by davidobrien1985** [serilog/serilog-settings-configuration#248]
Hi,

I managed to get serilog (with Seq) working with my Azure Functions v3 following the documentation adding the `Serilog` section into the `host.json`.
However, that's not really a great pattern IMO as I want a different config locally to when it is deployed.

Local: Seq
Prod: ApplicationInsights

For that the pattern is to put environment variables into `local.settings.json`.
However, I have no idea how I would then go about getting the `Serilog` config into the app then.

```
builder.Services.AddSingleton<ILoggerProvider>(sp =>
            {
                var functionDependencyContext = DependencyContext.Load(typeof(Startup).Assembly);

                var hostConfig = sp.GetRequiredService<IConfiguration>();
                var logger = new LoggerConfiguration()
                    .ReadFrom.Configuration(hostConfig, sectionName: "AzureFunctionsJobHost:Serilog", dependencyContext: functionDependencyContext)
                    .CreateLogger();

                return new SerilogLoggerProvider(logger, dispose: true);
            });
        }
```

This doesn't work, only works if I put the config into `host.json`.

Thanks!

**Comment by davidobrien1985** [comment]
Looks like this isn't supported in Azure Functions: https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local?tabs=windows%2Ccsharp%2Cbash#local-settings-file
The local settings file only supports simple key value pairs, no complex objects.

So what's the recommended way for Azure Functions to have one sink be used locally and another sink be used when in prod?

**Comment by jimmyville** [comment]
@davidobrien1985 If you're happy to use appsettings.json configuration instead of environment variables you can use the following example in your function startup class (similar to other .NET project types):

```csharp
public class Startup : FunctionsStartup
{
	public override void ConfigureAppConfiguration(IFunctionsConfigurationBuilder builder)
	{
		FunctionsHostBuilderContext context = builder.GetContext();
		
		builder.ConfigurationBuilder
			.AddJsonFile(Path.Combine(context.ApplicationRootPath, "appsettings.json"), optional: true, reloadOnChange: false)
			.AddJsonFile(Path.Combine(context.ApplicationRootPath, $"appsettings.{context.EnvironmentName}.json"), optional: true, reloadOnChange: false)
			.AddEnvironmentVariables();
        }
}
```

Make sure to instruct your project to copy these appsettings files to your output directory during build as this won't happen by default with function projects.
