### ISSUE TITLE
Placeholder for MachineName in path property

### ISSUE THREAD

**Issue by sascha-andres** [serilog/serilog-settings-configuration#249]
I try to configure Serlog in the appsettings to have the machinename as part of the logfile name. Unfortunately {MachineName} does not get replaced.

Bachground: I only have a common place to write logs to (on a network share) but scaling backend servers. Is there any way to do this using configuration

Thanks in advance

**Comment by skomis-mm** [comment]
Hi @sascha-andres ,

Sorry for the slow response.
You can use environment variables that will be expanded at startup:
```json
"path": "../%COMPUTERNAME%/Logs/app.log"
```
