### ISSUE TITLE
Custom or ThirdParty TextFormatter of error

### ISSUE THREAD

**Issue by ekwebster** [serilog/serilog-settings-configuration#250]
I need to output error logs in Elastic Common Schema. There is a [third party formater](https://github.com/elastic/ecs-dotnet/tree/master/src/Elastic.CommonSchema.Serilog), that will do this but I don't think its currently possible to load that into the args formatter something like this:
`"WriteTo": [
      {
        "Name": "Console",
        "Args": { "formatter": "Elastic.CommonSchema.Serilog.EcsTextFormatter" }
      }
]` 

Is there a way to do this?

**Comment by sungam3r** [comment]
You can write your wrapper-sink and set formatter from code. Then setup your sink with other args from settings.

**Comment by skomis-mm** [comment]
Hi @ekwebster ,

Sorry for the long delay. You need to specify assembly qualified name:
```json
"formatter": "Elastic.CommonSchema.Serilog.EcsTextFormatter, Elastic.CommonSchema.Serilog"
```
