### ISSUE TITLE
Unclear documentation for .net5 single file workaround

### ISSUE THREAD

**Issue by Meowzz95** [serilog/serilog-settings-configuration#252]
From the doc in README

>NET 5.0 Single File Applications
Currently, auto-discovery of configuration assemblies is not supported in bundled mode. Use Using section for workaround.

I have no idea what the `Using` section is referring to.

Could you suggest what the `Using` section is and even better, can we have some examples on how to implement the workaround in .NET5 single file?

**Comment by skomis-mm** [comment]
Hi @Meowzz95 ,

`Using` section is described [here](https://github.com/serilog/serilog-settings-configuration#using-section-and-auto-discovery-of-configuration-assemblies).

**Comment by Meowzz95** [comment]
Thanks for your update!
