### ISSUE TITLE
Unclear/confusing document on handling of appsettings.ENVIRONMENT.json files

### ISSUE THREAD

**Issue by R4cOOn** [serilog/serilog-settings-configuration#255]
I was following the samples (these are very helpful BTW!) and couldn't work out with my appsettings.Development.json configuration wasn't picked up even though I had the same initialisation code as you.

I was under the (very wrong) assumption that `.AddJsonFile("appsettings.json", false, true)` was clever enough to pick up `appsettings.Development.json` in my Development environment.
Some hours later I realised that it isn't and I had to add the line `.AddJsonFile($"appsettings.{Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT")}.json", true, true)` to get it to work.

It would be great if you could add the line (or a comment) in your sample.
That would hopefully help someone else wasting their time like I did.

Cheers.

**Comment by nblumhardt** [comment]
Done - thanks!
