### ISSUE TITLE
Environment variables in file path don't work on Linux

### ISSUE THREAD

**Issue by TehGM** [serilog/serilog-settings-configuration#257]
I have following config in my JSON file:
```csharp
"WriteTo": [
  {
    "Name": "Async",
    "Args": {
      "configure": [
        {
          "Name": "File",
          "Args": {
            "path": "%PROGRAMDATA%/TehGM/fsriev/logs/log-.log",
            "rollingInterval": "Day",
            "retainedFileCountLimit": 30,
            "fileSizeLimitBytes": 2097152,
            "rollOnFileSizeLimit": true,
            "buffered": false
          }
        }
      ]
    }
  }
]
```
This works as expected on Windows 10. However, when the application is ran on Debian, folder of name %PROGRAMDATA% is created instead. I also tried %APPDATA%:
![obraz](https://user-images.githubusercontent.com/9112561/113487480-9cc54780-94b8-11eb-9ff0-f34b08b9584b.png)

When using special folders feature using in-code configuration, they work perfectly fine.

Library version: **3.1.0**.

**Comment by diogocp** [comment]
Those environment variables don't exist on Debian by default. Did you set them yourself?

**Comment by TehGM** [comment]
No, didn't create them anywhere. Looking for a solution that works out of the box, so users of my applications don't need to make OS modifications themselves.

I know that .NET's native SpecialFolders enum supports these folders - but seems that Serilog.Settings.Configuration only uses environment variables. Is there any good workaround to this for Linux systems?

**Comment by nblumhardt** [comment]
`%VARNAME%` is also Windows-specific; on *nix, you'll need `$VARNAME` (https://github.com/serilog/serilog-settings-configuration/blob/dev/src/Serilog.Settings.Configuration/Settings/Configuration/StringArgumentValue.cs#L31).

Linux has its own set of well-known environment variables, like `$HOME`, that you can use on those systems.

**Comment by TehGM** [comment]
Ok, that's something. Non ideal, but something.

Is there anyworkaround that would work on both Windows and Linux? I want to keep a single configuration file for both, Windows and Linux, so it's within the same download.

**Comment by diogocp** [comment]
I would suggest configuring the defaults in code and leaving the user with the option to override the default by setting the path in the configuration file.
