### ISSUE TITLE
Dead lock when running in container AWS lambda environment

### ISSUE THREAD

**Issue by WarrenFerrell** [serilog/serilog-settings-configuration#258]
When deploying a .NET 5 container to AWS Lambda using Amazon.Lambda.RuntimeSupport `ConfigurationLoggerConfigurationExtensions.Configuration(this LoggerSettingsConfiguration settingConfiguration, IConfiguration configuration, DependencyContext dependencyContext = null)` never returns. I have not tracked down the exact issue or come up with a workaround (except just not using the Serilog Configuration package) because I have no need of dynamic loading of assemblies.

It would be really great if the dynamic assembly loading and settings loading pieces of Serilog.Settings.Configuration were separated into 2 packages. The dependency on Microsoft.Extensions.DependencyModel causes a huge headache and the package produces an extra 24 trim analysis warnings.

FYI saw this referencing both 3.1.0 and 3.2.0-dev-00266
packages were published using `dotnet publish -c Release --self-contained true -r linux-x64`

**Comment by skomis-mm** [comment]
Hi @WarrenFerrell ,

It seems trimming causes this. 

As a workaround you can try to use different overload to see if it helps
```csharp
new LoggerConfiguration()
     .ReadFrom.Configuration(configuration, ConfigurationAssemblySource.AlwaysScanDllFiles)
```
(should skip `Microsoft.Extensions.DependencyModel` usage) 

Or exclude `Microsoft.Extensions.DependencyModel` dependencies and its members from trimming:
```csharp
<ItemGroup>
    <TrimmerRootAssembly Include="Microsoft.Extensions.DependencyModel" />
</ItemGroup>
```

HTH!
