### ISSUE TITLE
System.MemberAccessException if enricher has static ctor

### ISSUE THREAD

**Issue by Tolyandre** [serilog/serilog-settings-configuration#260]
If a custom enricher has a static ctor, configuration throws `System.MemberAccessException : Type initializer was not callable.`

There is how I discovered such behavior:  https://github.com/Tolyandre/serilog-throw-context-enricher/issues/2

To reproduce with a unit test:
1. add empty static ctor to [DummyThreadIdEnricher](https://github.com/serilog/serilog-settings-configuration/blob/dev/test/TestDummies/DummyThreadIdEnricher.cs)
2. run test [EnrichWithIsAppliedWithCustomEnricher](https://github.com/serilog/serilog-settings-configuration/blob/dev/test/Serilog.Settings.Configuration.Tests/ConfigurationSettingsTests.cs#L1160)

Actual behavior: test throws
Expected behavior: enricher is instantiated

**Comment by nblumhardt** [comment]
Thanks for the report 👍
