### ISSUE TITLE
version

### ISSUE THREAD

**Issue by Vincent-NET** [serilog/serilog-settings-configuration#267]
hi guys. 

how can I tell which version is which in nuget.org? 

I am looking at 3.2.0 Release #238

not sure what's that mean or how match the version in nuget.org.

and anyone know estimate release date for 3.2.0 ?

sorry for the newbie questions :)

thank you.

**Comment by skomis-mm** [comment]
Hi @Vincent-NET ,

sorry for the long wait, 3.2.0 is finally released
