### ISSUE TITLE
Support encoding parameter

### ISSUE THREAD

**Issue by gandhis1** [serilog/serilog-settings-configuration#268]
The `encoding` parameter accepts an `Encoding` value, such as `Encoding.UTF8`. However when I put it in my _appsettings.json_ the conversion does not work:

`System.InvalidCastException: "Invalid cast from 'System.String' to 'System.Text.Encoding'"`

I'm surprised something so basic is not supported, so am I doing something wrong, or is it actually not supported?

Edit: I thought this was an enum, it actually isn't, it's a singleton....

**Comment by skomis-mm** [comment]
Hi @gandhis1 ,
correct syntax for such parameter should be [System.Text.Encoding::UTF8](https://github.com/serilog/serilog-settings-configuration/pull/77)

Will should update the documentation regarding this. 
HTH!
