### ISSUE TITLE
Azure Table Storage Configuration in Serilog.

### ISSUE THREAD

**Issue by AnandPrakash05** [serilog/serilog-settings-configuration#27]
Hi,
Could you please provide syntax  to put into appsettings.json for the Azure Table Storage Configuration ?

Thank You!!

**Comment by nblumhardt** [comment]
Hi Anand,

I believe you need:

```json
    "WriteTo": [
      {"Name": "AzureTableStorage", "Args": {"connectionString": "<connection string>"}}
    ]
```

I don't know much about this sink, but if the above doesn't get you started let me know.

Cheers,
Nick

**Comment by AnandPrakash05** [comment]
Thank You Nick for quick response.
I will try and let you know.

**Comment by AnandPrakash05** [comment]
It worked :) Thanks!!

  "Serilog": {
    "MinimumLevel": "Debug",
    "WriteTo": [
      {
        "Name": "AzureTableStorage",
        "Args": {
          "storageTableName": "",
          "connectionString": "<connection string>"
        }
      }
    ]
  }

**Comment by nblumhardt** [comment]
Added to the docs :-) https://github.com/serilog/serilog-sinks-azuretablestorage#json-configuration

Thanks!
