### ISSUE TITLE
Default output template for ALL providers

### ISSUE THREAD

**Issue by RomanIvasyk** [serilog/serilog-settings-configuration#270]
Is it possible to override the default output template for all providers? For now, I forced to set the same template for all providers explicitly
![image](https://user-images.githubusercontent.com/42912527/123323082-b6b57a00-d53d-11eb-93ee-93e930b7bc8e.png)

**Comment by skomis-mm** [comment]
Hi @RomanIvasyk ,
No, it is not supported via configuration syntax.
