### ISSUE TITLE
Access LoggingLevelSwitch at runtime

### ISSUE THREAD

**Issue by pmiddleton** [serilog/serilog-settings-configuration#272]
Is there anyway to programmatically access LoggingLevelSwitch-es configured in the config json?  I want to be able to change the logging level at runtime in my service via a web service call.  

I see that the LoggingLevelSwitch are stored in a ResolutionContext inside of the IConfigurationReader.  However I don't see a way outside of reflection to access them.  Am I missing something, or is changing them via a file watcher on the config json the only way to change them at runtime?

**Comment by skomis-mm** [comment]
Hi @pmiddleton ,
currently there is no way unless to get it via reflection, tracked #206
