### ISSUE TITLE
Extend ConfigurationReader?

### ISSUE THREAD

**Issue by markolbert** [serilog/serilog-settings-configuration#277]
I have a wrapper for Serilog which adds source code references to log events. It has its own IConfiguration-based system...which is redundant with serilog-settings-configuration :). But my wrapper needs some additional configuration info to work.

Is it possible to extend ConfigurationReader so that I can capture my custom/additional config info? I realize I could simply read the config file (json) twice but if there's a way to avoid that I'd like to do so.

**Comment by skomis-mm** [comment]
Hi @markolbert , 
there is no way since types are internal and at this point are subject to change.

**Comment by markolbert** [comment]
Thanx for the quick response.
