### ISSUE TITLE
System.TypeLoadException: Method 'Verbose' in type 'Serilog.Extensions.Hosting.ReloadableLogger' from assembly 'Serilog.Extensions.Hosting'

### ISSUE THREAD

**Issue by klyse** [serilog/serilog-settings-configuration#288]
# Installed nuget packages

```
<PackageReference Include="AspNetCore.HealthChecks.NpgSql" Version="5.0.2" />
<PackageReference Include="FluentValidation.AspNetCore" Version="10.3.4" />
<PackageReference Include="MediatR.Extensions.Microsoft.DependencyInjection" Version="9.0.0" />
<PackageReference Include="Sentry.AspNetCore" Version="3.10.0" />
<PackageReference Include="Sentry.Serilog" Version="3.9.3" />
<PackageReference Include="Serilog" Version="2.10.0" />
<PackageReference Include="Serilog.AspNetCore" Version="4.1.0" />
<PackageReference Include="Serilog.Extensions.Hosting" Version="4.2.0" />
<PackageReference Include="Serilog.Extensions.Logging" Version="3.1.0" />
<PackageReference Include="Serilog.Formatting.Compact" Version="1.1.0" />
<PackageReference Include="Serilog.Settings.Configuration" Version="3.3.0" />
<PackageReference Include="Serilog.Sinks.Console" Version="4.0.0" />
<PackageReference Include="Serilog.Sinks.Debug" Version="2.0.0" />
<PackageReference Include="Serilog.Sinks.File" Version="5.0.0" />
<PackageReference Include="Serilog.Sinks.Fluentd" Version="0.4.0" />
<PackageReference Include="Serilog.Sinks.PeriodicBatching" Version="2.3.0" />
<PackageReference Include="Swashbuckle.AspNetCore" Version="6.2.3" />
```

Also tried with a more minimalistic set of nugets:

```
<PackageReference Include="AspNetCore.HealthChecks.NpgSql" Version="5.0.2" />
<PackageReference Include="FluentValidation.AspNetCore" Version="10.3.4" />
<PackageReference Include="MediatR.Extensions.Microsoft.DependencyInjection" Version="9.0.0" />
<PackageReference Include="Sentry.AspNetCore" Version="3.10.0" />
<PackageReference Include="Sentry.Serilog" Version="3.10.0" />
<PackageReference Include="Serilog.AspNetCore" Version="4.1.0" />
<PackageReference Include="Serilog.Sinks.Fluentd" Version="0.4.0" />
<PackageReference Include="Swashbuckle.AspNetCore" Version="6.2.3" />
```

# OS

Docker

`mcr.microsoft.com/dotnet/aspnet:5.0`

# Additional Information

ASP.Net Core 5.0 app running in a docker container

# Code

``` C#
private static LoggerConfiguration ConfigureLogger(LoggerConfiguration loggerConfig)
{
	loggerConfig
		.MinimumLevel.Override("Microsoft", LogEventLevel.Warning)
		.MinimumLevel.Override("Microsoft.EntityFrameworkCore", LogEventLevel.Warning)
		.MinimumLevel.Override("Microsoft.AspNetCore.SignalR", HostingEnvHelper.IsDevelopment ? LogEventLevel.Debug : LogEventLevel.Warning)
		.MinimumLevel.Override("Microsoft.AspNetCore.Http.Connections", HostingEnvHelper.IsDevelopment ? LogEventLevel.Debug : LogEventLevel.Warning)
		.Enrich.FromLogContext()
		.WriteTo.Sentry()
		.WriteTo.Console();

	return loggerConfig;
}

public static int Main(string[] args)
{
	// Serilog.Debugging.SelfLog.Enable(Console.WriteLine);
	Log.Logger = ConfigureLogger(new LoggerConfiguration())
		.MinimumLevel.Debug()
		.CreateBootstrapLogger();
    ....
}
....
public static IHostBuilder CreateHostBuilder(string[] args) =>
	Host.CreateDefaultBuilder(args)
		.ConfigureWebHostDefaults(webBuilder =>
		{
			webBuilder
				.UseStartup<Startup>()
				.UseSentry()
				.UseUrls("http://+:5003");
		})
		.UseSerilog((context, _, configuration) =>
			ConfigureLogger(configuration)
				.ReadFrom.Configuration(context.Configuration));
```

# Exception

```
root@f342f6bbdb2a:/app# dotnet Web.dll
Unhandled exception. System.TypeLoadException: Method 'Verbose' in type 'Serilog.Extensions.Hosting.ReloadableLogger' from assembly 'Serilog.Extensions.Hosting, Version=2.0.0.0, Culture=neutral, PublicKeyToke
n=24c2f752a8e58a10' does not have an implementation.
Aborted
```

# Steps tried to resolve the issue

* Install different versions of the serilog nuget packages
* Removed all config from `appsettings.*.json`
* Different container versions: `mcr.microsoft.com/dotnet/aspnet:5.0.12`, `mcr.microsoft.com/dotnet/aspnet:5.0.5` and some more
* Multiple docker builds with `--no-cache`

# Hint to where the problem comes from

When changing `.CreateBootstrapLogger()` to `CreateLogger()` and adjusting `CreateHostBuilder` of course the issue is gone.

**Comment by klyse** [comment]
Found the solution myself. The `.dockerignore` did not exclude build results and therefore copied the binaries into the container which led to this issue.

Here is the  `.dockerignore`  that worked for us:
```
Web/appsettings.[Dd]evelopment.json
*.env
.envrc
.git
.dockerignore
.gitignore
.vs
.vscode
docker-compose.yml
docker-compose.*.yml
*/bin
*/obj
```

**Comment by klyse** [comment]
Having the correct `.dockerignore` did not solve the issue it just stays the same.
I made the test on a wrong branch. Sorry for the confusion.

**Comment by klyse** [comment]
After some more hours of debugging I found the problem. Finally.

Here is a repo to reproduce the problem: https://github.com/klyse/Serilog-Version-Bug

A lib targeting `netstandard2.0` loaded `Serilog 2.10.0` while the main project targets `net5/6.0` and loaded`Serilog.AspNetCore 4.1.0`. `CreateBootstrapLogger()` then tries to resolve a wrong dll and the app does not start.

**Comment by skomis-mm** [comment]
@klyse , interesting... 
It looks like the published version of `Serilog.dll` comes from `netstandard2.0` package folder instead of `netstandard2.1`.
Can you check this via reflection tool like `ILSpy`?
![image](https://user-images.githubusercontent.com/15090984/142759904-f63e57b4-51db-4669-bd63-80de2dfee150.png)

Is it happens only from docker environment? Looks like tooling issue, could not reproduce it yet.. (unless manually copy `Serilog.dll` of `netstandard2.0` to the output folder)

**Comment by skomis-mm** [comment]
Ok, just change the line
```
dotnet publish -c Release -o out
```
to

```
 dotnet publish web -c Release -o out
```

I read somewhere that `publish` on `.sln` is not a recommended way because can have unpredicted results. (`Lib` published artifacts overwrites `Web` artifacts). At least, in current tooling (check `dotnet/sdk`) .
Instead, do your publish just for the end project (`Web`)

**Comment by klyse** [comment]
That did the trick! This is awesome, thanks @skomis-mm! I guess the `ILSpy` is not required anymore.?

**Comment by skomis-mm** [comment]
@klyse  Great! 
No, `ILSpy` is not required anymore :)
