### ISSUE TITLE
Arguments binding using dependency injection

### ISSUE THREAD

**Issue by pmiddleton** [serilog/serilog-settings-configuration#290]
Is it possible to use dependency injection during argument binding?

I have implemented a custom ITextFormatter and I want to inject another of my services which is registered with the aspnet DI engine.  From what I have been able to figure out it appears this is not supported.  Is this correct?

**Comment by skomis-mm** [comment]
Hi @pmiddleton ,
Yes, it's correct, DI is not supported.

**Comment by pmiddleton** [comment]
Thank you.

**Comment by ADIX7** [comment]
Will this be supported? Or is there any reason it shouldn't be?
