### ISSUE TITLE
NU1605 error for .Net 6 and nuget packet Serilog.AspNetCore 4.1.0

### ISSUE THREAD

**Issue by JanRou** [serilog/serilog-settings-configuration#292]
This ps command  _dotnet publish --self-contained -r win10-x64_ triggers among others similar:

` error NU1605:  MyWebApiProject -> Serilog.AspNetCore 4.1.0 -> Serilog.Settings.Configuration 3.1.0 -> Microsoft.Extensions.DependencyModel 2.0.4 -> Microsoft.DotNet.PlatformAbstractions 2.0.4 -> System.IO.FileSystem 4.0.1 -> runtime.win.System.IO.FileSystem 4.3.0 -> System.Collections (>= 4.3.0)`

The ps command works when Serilog nuget packet Serilog.AspNetCore 4.1.0 is removed from the project, MyWebApiProject. It's same situation for version 4.1.1-dev-0241 for Serilog.AspNetCore.

**Comment by skomis-mm** [comment]
Hi, @JanRou ,
looks like a dup of #196 
Try install latest `serilog.settings.configuration` version, along with the `Serilog.AspNetCore` project.

**Comment by JanRou** [comment]
> Hi, @JanRou , looks like a dup of #196 Try install latest `serilog.settings.configuration` version, along with the `Serilog.AspNetCore` package.

Thank you!
It worked. 
Please close the issue!
