### ISSUE TITLE
Microsoft.Extensions.DependencyModel update for .net 6

### ISSUE THREAD

**Issue by hasandogu** [serilog/serilog-settings-configuration#294]
I have just updated our Azure function to start using .net 6 in-process. We have been using serilog successfully in our function. However, we cannot use the configuration file for serilog settings any more. 

As soon as we enable `.ReadFrom.Configuration(config)`, Azure functions host will fail with the following:

`
[2022-01-03T05:44:27.302Z] Could not load file or assembly 'Microsoft.Extensions.DependencyModel, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified. Value cannot be null. (Parameter 'provider')
`

This is with me updating our Nugets to the latest version. However, it does the same thing with Version=3.0.0.0 as well.

Would this mean an update to the DependencyModel would be needed in this library? Any help would be appreciated.

**Comment by skomis-mm** [comment]
Hi @hasandogu ,
try [this](https://github.com/serilog/serilog-settings-configuration/pull/222#issuecomment-919916935) workaround

**Comment by neils-swiftid** [comment]
> I have just updated our Azure function to start using .net 6 in-process. We have been using serilog successfully in our function. However, we cannot use the configuration file for serilog settings any more.
> 
> As soon as we enable `.ReadFrom.Configuration(config)`, Azure functions host will fail with the following:
> 
> `[2022-01-03T05:44:27.302Z] Could not load file or assembly 'Microsoft.Extensions.DependencyModel, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified. Value cannot be null. (Parameter 'provider')`
> 
> This is with me updating our Nugets to the latest version. However, it does the same thing with Version=3.0.0.0 as well.
> 
> Would this mean an update to the DependencyModel would be needed in this library? Any help would be appreciated.

Having the same issue, haven't tried the work around mentioned by @skomis-mm .
It would be really nice for this to be updated

**Comment by skomis-mm** [comment]
Hi @neils-swiftid,
workaround should do the trick. 

The problem with updating  'Microsoft.Extensions.DependencyModel` in this package is it won't work if the version will be overriden in the end project or .net runtime (3.1, for example) or via some other package that depends on 'Microsoft.Extensions.DependencyModel`.
