### ISSUE TITLE
FileNotFoundException when using Serilog.Settings.Configuration in an Azure Function in .NET 6

### ISSUE THREAD

**Issue by fgheysels** [serilog/serilog-settings-configuration#297]
I created an Azure Function which is running on .NET 6.  My Azure Function uses Serilog for logging and I'm using Serilog.Settings.Configuration to read log settings from the configuration.

When running the Function, I run into this exception:

```
System.IO.FileNotFoundException: 'Could not load file or assembly 'Microsoft.Extensions.DependencyModel, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.'
```

I do see that the Serilog.Settings.Configuration package has a dependency on Microsoft.Extensions.DependencyModel v3.0.0.0 but this might maybe conflict with .NET 6 ?

![image](https://user-images.githubusercontent.com/3605786/148958673-47729d52-dfbd-4df3-afcf-6c4167f9ea19.png)

**Comment by fgheysels** [comment]
I have worked around this for now by:
- explicitly adding a dependency on the package Microsoft.Extensions.DependencyModel v6.0.0
- specify this Property in my Function's csproj file:
        ```
       <PropertyGroup>
		<_FunctionsSkipCleanOutput>true</_FunctionsSkipCleanOutput>
	</PropertyGroup>
	```

**Comment by fgheysels** [comment]
It's a workaround but not a clean solution imho.

**Comment by krzysiek-b** [comment]
It seems not work any more on latest dotnet tools. Can anyone confirm?

**Comment by fgheysels** [comment]
> It's a workaround but not a clean solution imho.

If I'm not mistaken, isolated Functions should solve this issue ?

**Comment by sergiojrdotnet** [comment]
@krzysiek-b I've tested today and it still working
