### ISSUE TITLE
Update to RC2

### ISSUE THREAD

**Issue by ciwchris** [serilog/serilog-settings-configuration#3]
Will this be updated to RC2 or is there another preferred way of reading settings from a configuration file? Currently I'm receiving the error:

> Reference to type 'ILibraryManager' claims it is defined in 'Microsoft.Extensions.PlatformAbstractions', but it could not be found

Because this is using "Microsoft.Extensions.PlatformAbstractions": "1.0.0-rc1-final"

**Comment by nblumhardt** [comment]
Hi Chris - yes, definitely. There's a bit of a backlog of things to update for RC2 right now, trying to get to this one ASAP :-)

Cheers!

**Comment by ciwchris** [comment]
Thanks, I thought that was probably the case. When RC2 released it created a lot of work. I see you've already been hard at work updating other libraries.

**Comment by nblumhardt** [comment]
Almost there with this one; just need to figure out how to replace the use of  `ILibraryManager` and `PlatformServices.Default.LibraryManager` with `DependencyContext` in https://github.com/serilog/serilog-settings-configuration/blob/master/src/Serilog.Settings.Configuration/ConfigurationLoggerConfigurationExtensions.cs#L58 ...

**Comment by nblumhardt** [comment]
@ciwchris PR linked above; it'd be great to have another set of eyes on it, if you have a chance to look it over. Shouldn't be far away now.

**Comment by khellang** [comment]
Fixed with #4 :smile:

**Comment by ciwchris** [comment]
Thanks @nblumhardt for such a quick turn around! Much appreciated!
