### ISSUE TITLE
ReadFrom.Configuration is not working if serilog tag is not at parent Node

### ISSUE THREAD

**Issue by sachin-agarwal-by** [serilog/serilog-settings-configuration#302]
If we have configured serilog from the appsettings and I have added Serilog element not at the root level like below in appsettings, then the logging is not working .. any help or comment please ..

appsettings.cs
`"test": {
      "Serilog": {
        "Using": [ "Serilog.Sinks.Console" ],
        "MinimumLevel": "Information",
        "WriteTo": [
          { "Name": "Console" },
          {
            "Name": "File",
            "Args": { "path": "Logs/log.txt" }
          }
        ]
      }
    }`

Program.cs
`public static IHostBuilder CreateHostBuilder(string[] args) =>
           Host.CreateDefaultBuilder(args)
                .UseSerilog((context, services, configuration) => configuration
                    .ReadFrom.Configuration(context.Configuration,sectionName: "test: Serilog")
                    .ReadFrom.Services(services))
                   .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                });
    }`

**Comment by sungam3r** [comment]
`"test: Serilog"` -> `"test:Serilog"`

**Comment by sachin-agarwal-by** [comment]
thanks a lot .. its working after removing spaces
