### ISSUE TITLE
ConfigurationReader.FindConfigurationExtensionMethods relies on one specific implementation of ExtensionAttribute

### ISSUE THREAD

**Issue by sajagi** [serilog/serilog-settings-configuration#306]
The method (`ConfigurationReader.FindConfigurationExtensionMethods`) should not rely on specific `ExtensionAttribute` type present in `System.Runtime.dll`, but rather on any type with matching name.

The attribute can be polyfilled in any assembly to enable extension method support.

In one (my) case this attribute is implemented in `nunit.engine.core` assembly which leads Serilog to not recognize extension methods when running tests using e.g. nunit3-console. 

Happy to provide a PR.

**Comment by nblumhardt** [comment]
PR would be great, thanks. We should be able to squeeze this into #299.
