### ISSUE TITLE
Formatter support

### ISSUE THREAD

**Issue by nblumhardt** [serilog/serilog-settings-configuration#31]
From: https://nblumhardt.com/2016/07/serilog-2-0-json-improvements/#comment-2988455879

It appears that this package doesn't yet support the `formatter` arg necessary for configuring e.g. JSON formatting for a rolling file sink.

**Comment by skomis-mm** [comment]
Just checked with proposed config - works as expected on `2.1+`. Need more info on this

**Comment by nblumhardt** [comment]
Confirmed working by the OP. (Thanks @skomis-mm )
