### ISSUE TITLE
Release v3.3.1 ETA?

### ISSUE THREAD

**Issue by crozone** [serilog/serilog-settings-configuration#322]
The README.md is currently out of sync with the current 3.3.0 release package.

Attempting to use the code example to pass an array of configuration assemblies (eg. for .NET 6 single file apps with trimming) currently doesn't compile:

```csharp
var configurationAssemblies = new[]
{
    typeof(ConsoleLoggerConfigurationExtensions).Assembly,
    typeof(FileLoggerConfigurationExtensions).Assembly,
};
var logger = new LoggerConfiguration()
    .ReadFrom.Configuration(configuration, configurationAssemblies)
    .CreateLogger();
```

The last commit was in May, any ETA on when the 3.3.1 package might be going live?

**Comment by nblumhardt** [comment]
Tracked here: https://github.com/serilog/serilog-settings-configuration/pull/299

Thanks for the nudge; mostly just waiting on getting some release notes together, I'll check it out now.
