### ISSUE TITLE
Multiple appsettings.json not override MinimumLevel property

### ISSUE THREAD

**Issue by kaioanselmo** [serilog/serilog-settings-configuration#328]
If i have:

appsettings.json
```javascript
{
  Serilog: {
    MinimumLevel: "Warning"
  }
}
```

and

appsettings.Development.json
```javascript
{
  Serilog: {
    MinimumLevel: {
      Default: "Information"
    }
  }
}
```

When creating the Logger:
```csharp
var configuration = new ConfigurationBuilder()
    .AddJsonFile("appsettings.json")
    .AddJsonFile("appsettings.Development.json")
    .Build();
Log.Logger = new LoggerConfiguration()
    .ReadFrom.Configuration(configuration)
    .CreateLogger();
```

At the end, when running in Debug, MinimumLevel will be only "Warning" and not "Information"

**Comment by SimonCropp** [comment]
@nblumhardt should multiple calls to `AddJsonFile` result in a last one wins?

**Comment by nblumhardt** [comment]
Last-in wins, but in this case there are two different keys in the result - `Serilog.MinimmLevel` and `Serilog.MinimumLevel.Default`; Serilog just sees the final output from Microsoft.Extensions.Configuration and can't tell which is "more specific".

Using `Serilog.MinimumLevel.Default` in both files will give you the result you want.
