### ISSUE TITLE
Updating MinimumLevel during runtime.

### ISSUE THREAD

**Issue by strohhut** [serilog/serilog-settings-configuration#33]
When the configuration changes because an appsettings.json file was changed and `AddJsonFile.reloadOnChange` is `true`, is it possible that this change is picked up on the fly? Something like a configuration watch based switch?

**Comment by skomis-mm** [comment]
@stronhut, yes, it should work that way already when you specify 'reloadOnChange=true'

**Comment by strohhut** [comment]
You are right it works. Seems like I did something wrong on my initial test of this (I'm new to serilog).

This feature is very important. I think it would be good to add the info about `reloadOnChange` to the serilog-settings-configuration readme so that it can't be missed.
