### ISSUE TITLE
It's possible to read "credentials/sensitive info" from environment variables?

### ISSUE THREAD

**Issue by igorgomeslima** [serilog/serilog-settings-configuration#345]
Serilog Settings Configuration([Serilog.Sinks.Datadog.Logs](https://github.com/DataDog/serilog-sinks-datadog-logs#configuration-from-appsettingsjson)):

Sample: 
```
"Serilog": {
  "Using": [ "Serilog.Sinks.Datadog.Logs" ],
  "MinimumLevel": "Debug",
  "WriteTo": [
    { "Name": "Console" },
    {
      "Name": "DatadogLogs",
      "Args": {
        //"apiKey": "<API_KEY>",
        "apiKey": "${READ_IT_FROM_ENVIRONMENT_VARIABLE:VARIABLE_NAME}", //<- This approach does not exist/does not work.
      }
    }
  ],
  "Enrich": [ "FromLogContext", "WithMachineName", "WithThreadId" ],
  "Properties": {
    "Application": "Sample"
  }
}
```
We have something similar in NLog: `${environment:ENVIRONMENT_VARIABLE_NAME}`.

[Environment layout renderer](https://github.com/NLog/NLog/wiki/Environment-Layout-Renderer)

Sample:

NLog.config([NLog.Targets.ElasticSearch](https://github.com/markmcdowell/NLog.Targets.ElasticSearch))
```
...
<target xsi:type="ElasticSearch"
                ...
                username="${environment:ELASTICSEARCH_USER}"
                password="${environment:ELASTICSEARCH_PASSWORD}"
                layout="${verbose}">
          <field name="host" layout="${machinename}"/>
        </target>
...
```

**Comment by nblumhardt** [comment]
This is provided natively by _Microsoft.Extensions.Configuration_; I think the variable you'd need to set in this case is something like `SERILOG__WRITETO__1__ARGS__APIKEY`.

Might need a bit of digging around, unfortunately setting values in arrays using environment variables can be awkward. HTH!

**Comment by igorgomeslima** [comment]
@nblumhardt TFYT! Any documentation about it?

**Comment by igorgomeslima** [comment]
Thank's for insights guys! I know about the "Configuration", when I mentioned "Documentation" I meant specifically to "How read from appsettings using `index`? How index works in appsettings? Any official sample at DOC's, like `Serilog__WriteTo__1__Args__apiKey` or similar?". Anyway, it's help. 😀

**Comment by 0xced** [comment]
It's all in the [Configuration in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/configuration/) documentation. Look at [Bind an array](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/configuration/#bind-an-array) and [Naming of environment variables](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/configuration/#naming-of-environment-variables) specifically.
