### ISSUE TITLE
Serilog seq configuration is not reloaded when Seq serverUri is updated in appsettings.json file

### ISSUE THREAD

**Issue by bigswede74** [serilog/serilog-settings-configuration#346]
**Description**

I have a windows application that is logging using the Serilog.Sinks.Seq. All the configuration is coming from the appsettings.json file however when I update the serverUri while the application is running the configuration is not dynamically reloaded until the application is restarted. Does the seq sink support dynamic configuration updates for the serverUri?

**Reproduction**
- Create a console application
- Add Serilog, Serilog.Settings.Configuration, Microsoft.Extensions.Configuration.Json packages
- Add the appsettings.json file with reloadOnChange = true
- Build serilog from the configuration
- Change the seqUri while the application is running

Program.cs

```csharp 

private ILogger _logger;
private IConfiguration _configuration; 

public static void Main(string[] args)
{
    var builder = new ConfigurationBuilder()
        .SetBasePath(Directory.GetCurrentDirectory())
        .AddJsonFile("appsettings.json", optional: false, reloadOnChange: true);
    
    _configuration = builder.Build();
    
    _logger = new LoggerConfiguration()
        .ReadFrom.Configuration(_configuration)
        .CreateLogger();
    
    Log.Logger = _logger;
}
```

appsettings.json
```json
{
    "Serilog": {
        "Using": [ "Serilog.Sinks.Console", "Serilog.Sinks.File", "Serilog.Sinks.Seq" ],
        "MinimumLevel": "Information",
        "WriteTo": [
            {
                "Name": "Console"
            },
            {
                "Name": "File",
                "Args": {
                    "path": "C:\\logs\\myApp-.log",
                    "fileSizeLimitBytes": 200000000,
                    "rollOnFileSizeLimit": true,
                    "rollingInterval": "Day",
                    "retainedFileCountLimit": 14
                }
            },
            {
                "Name": "Seq",
                "Args": {
                    "serverUrl": "http://localhost:5341"
                }
            }
        ],
        "Enrich": [ "FromLogContext", "FromGlobalLogContext" ],
        "Destructure": [
            {
                "Name": "ToMaximumDepth",
                "Args": {
                    "maximumDestructuringDepth": 20
                }
            }
        ],
        "Properties": {
            "ApplicationName": "MyApp"
        }
    }
}
```

**Expected behavior**
Logs should be forwarded to the new seq address

**Relevant package, tooling and runtime versions**
Packages
- Microsoft.Extensions.Hosting 7.0.0
- Microsoft.Extensions.Hosting.WindowsServices 7.0.0
- Serilog 2.12.0
- Serilog.Settings.Configuration 3.4.0
- Serilog.SInks.Console 4.1.0
- Serilog.Sinks.Seq 5.2.2
 
Platform
- Windows 10

**Comment by nblumhardt** [comment]
Hi! AFAIK, _Serilog.Settings.Configuration_ only supports reloading a small number of settings at runtime (minimum level being the one I know of). I don't think there's any support for reloading sink arguments like these. HTH!

**Comment by bigswede74** [comment]
> 

Thanks for the quick response. Any recommendations on how I can accomplish this would be welcome. Should I just re-initialize a new logger and replace it in the DI container?

**Comment by SimonCropp** [comment]
restart the app
