### ISSUE TITLE
Missing rendered messsage when logging using LogEvent

### ISSUE THREAD

**Issue by yohny** [serilog/serilog-settings-configuration#374]
I have a project where some logs are produced using `LogEvent` and I noticed that in those cases the renderd message (message template with injected values of propeties) is missing.
To reproduce, try logging the following messages in regular and LogEvent fasion: 
```csharp
Log.Warning("my log message 1");
Log.Write(new LogEvent(
           DateTimeOffset.Now,
           LogEventLevel.Warning,
           null,
           new MessageTemplate("my log message 2", Enumerable.Empty<MessageTemplateToken>()),
           Enumerable.Empty<LogEventProperty>()));
```
Using the following `ExpressionTemplate`: `"{ {@t, @l, @mt, @m, @x, ..@p} }\n"` and the result is:
```plain
{"@t":"2023-04-17T16:32:15.5767953+02:00","@l":"Warning","@mt":"my log message 1","@m":"my log message 1","ThreadId":1,"Application":"my-app"}
{"@t":"2023-04-17T16:32:15.5799729+02:00","@l":"Warning","@mt":"my log message 2","@m":"","ThreadId":1,"Application":"my-app"}
```
As you can see in the second line logged using `LogEvent` the `@m` value is empty, althout it is expected to contain the rendered message (in this case the same as message template as there are no tokens present). This also happens when using `RenderedCompactJsonFormatter` - rendered message is empty.

**Comment by nblumhardt** [comment]
Hi @yohny - your message template is incorrectly constructed: even if it doesn't include any property placeholders, it should at least have one `MessageTemplateTextToken` with the full text of the template in it.

Using `MessageTemplateParser` to create the `MessageTemplate` will sidestep any other similar problems.
