### ISSUE TITLE
Minimum netstandard version

### ISSUE THREAD

**Issue by MichaCo** [serilog/serilog-settings-configuration#38]
Hey,
Is there any particular reason to target netstandard1.6? Seems netstandard1.3 would be totally cool too as no dependencies require 1.6

Thanks

**Comment by nblumhardt** [comment]
May have been historical. Happy to accept a PR if you can get the version requirements down 👍

**Comment by MichaCo** [comment]
@nblumhardt Seems that Microsoft.Extensions.DependencyModel 1.1.0 has netstandard1.3 target but they ifdef out the Default dependency context for whatever reason and [you seem to relay on that](https://github.com/serilog/serilog-settings-configuration/blob/dev/src/Serilog.Settings.Configuration/ConfigurationLoggerConfigurationExtensions.cs#L63).

So, in short, bad luck and 1.6 is actually needed -.-
