### ISSUE TITLE
Default formatter overrided by JSON formatter when using appsetting.json

### ISSUE THREAD

**Issue by AdisonCavani** [serilog/serilog-settings-configuration#382]
I want to use `JSON formatter` in production, but preserve `default formatter` in development.
In prod, everything is fine, but in development it's still using `JSON formatter`.

How can I use `default formatter` with this configuration?

I'm using this configuration files.

```cs
builder.Host.UseSerilog((ctx, cfg) => cfg.ReadFrom.Configuration(ctx.Configuration));
```

`appsettings.json`:

```json
{
  "Serilog": {
    "Using": [ "Serilog.Sinks.Console" ],
    "MinimumLevel": {
      "Default": "Information"
    },
    "WriteTo": [
      {
        "Name": "Console",
        "Args": {
          "formatter": "Serilog.Formatting.Compact.RenderedCompactJsonFormatter, Serilog.Formatting.Compact"
        }
      }
    ],
    "Enrich": [ "FromLogContext", "WithThreadId" ]
  }
}
```

`appsettings.development.json`:

```json
{
  "Serilog": {
    "Using": [ "Serilog.Sinks.Console" ],
    "MinimumLevel": {
      "Default": "Information"
    },
    "WriteTo": [
      {
        "Name": "Console"
      }
    ],
    "Enrich": [ "FromLogContext", "WithThreadId" ]
  }
}
```

**Comment by nblumhardt** [comment]
The trick to successful dev/prod configuration with this library is not to put much (or anything at all) related to Serilog in `appsettings.json`. Rather, put full configurations in each of `appsettings.Development.json` and `appsettings.Production.json`. This will avoid a whole range of quirky interactions between the two setups.

Hope this helps,
Nick

**Comment by AdisonCavani** [comment]
I managed to resolve the issue by adding default theme to args.
