### ISSUE TITLE
Configure JsonFormatter parameters via appsettings.json

### ISSUE THREAD

**Issue by johannesmols** [serilog/serilog-settings-configuration#392]
PR #281 added support for constructor parameters in appsettings.json. However, attempting to do this with the JsonFormatter gives an `InvalidOperationException` as described by @WattsC-90 [here](https://github.com/serilog/serilog-settings-configuration/pull/281#issuecomment-1220848169). It seems that there a few that have the same issue, and I do too now. Since the PR is merged, I am opening a new issue to get attention to this.

**Comment by FaroukOyekunle** [comment]
Where you able to complete the solution to this issues @johannesmols.

**Comment by johannesmols** [comment]
Hi @FaroukOyekunle, I forgot all about this one. The newest comment on the linked issue actually resolves it in my case: https://github.com/serilog/serilog-settings-configuration/pull/281#issuecomment-1684277040. I was also missing the "Serilog" behind the type of the formatter.

**Comment by FaroukOyekunle** [comment]
Cool! That's right.
