### ISSUE TITLE
Add configuring destructuring to the README file

### ISSUE THREAD

**Issue by satrapu** [serilog/serilog-settings-configuration#393]
Hello,

It seems that my blog post mentioning configuring Serilog destructuring policies via JSON configuration file caught some attention, as seen on [this LinkedIn thread](https://www.linkedin.com/feed/update/urn:li:ugcPost:7087271602316296192?commentUrn=urn%3Ali%3Acomment%3A%28ugcPost%3A7087271602316296192%2C7087330351647195137%29&replyUrn=urn%3Ali%3Acomment%3A%28ugcPost%3A7087271602316296192%2C7087713357704626176%29&dashCommentUrn=urn%3Ali%3Afsd_comment%3A%287087330351647195137%2Curn%3Ali%3AugcPost%3A7087271602316296192%29&dashReplyUrn=urn%3Ali%3Afsd_comment%3A%287087713357704626176%2Curn%3Ali%3AugcPost%3A7087271602316296192%29). 
Since the README does not cover this topic, I'm thinking to create a PR to add a new section called **Destructuring** under **Syntax description**, right after **Nested configuration sections** - would this be a good place? If not, where should I add it?

**Comment by satrapu** [comment]
Since I haven't received any replies yet, I took the liberty of opening a PR with the new section documenting how to configure destructuring: #396.

**Comment by FaroukOyekunle** [comment]
Hello @satrapu,

Thank you for taking the initiative to address the documentation gap by opening a pull request (#396). Adding the new section on configuring destructuring is greatly appreciated. This kind of contribution enhances the overall usability and clarity of the project for all users.

**Comment by satrapu** [comment]
Closing this issue since PR #396 has been merged and there is a new section documenting how to configure destructuring: https://github.com/serilog/serilog-settings-configuration#destructuring.
