### ISSUE TITLE
I want to configure the specified level of log output to a specified file in .net8 appsetting.sjon

### ISSUE THREAD

**Issue by 545867454** [serilog/serilog-settings-configuration#418]
I want to configure the specified level of logs to be output to a specified file in .net8 appsetting.sjon, but I configured it according to expression, but the Information Debug Error level is all output to a single file. How do I configure it?

**Comment by bartelink** [comment]
The best place to ask questions like this is on stackoverflow.com - if you tag them `serilog`, many more than the people watching here will see them, and others can benefit from any answers.

Note you're best off to include some details as to what you've tried so far, and explain in some more detail what exactly it is you're after.

Feel free to post a link to the SO question here when you're done.
