### ISSUE TITLE
RollingFile + JsonFormatter from config = plain text logs

### ISSUE THREAD

**Issue by andersnm** [serilog/serilog-settings-configuration#42]
Am unable to enable the JsonFormatter with RollingFile from a configuration file. Any insight would be appreciated, presumably I'm missing something obvious

Have updated all package versions, made sure to using "formatter" as the type parameter, and carefully pasted the typename per the only documentation I could find:
http://stackoverflow.com/questions/40880261/configuring-serilog-rollingfile-with-appsettings-json
https://github.com/serilog/serilog-settings-configuration/issues/31

Have tried to delete all Serilog.* packages from my .nuget folder and refresh. Have tried both older/newer version of the serilog and configuration packages. Made no difference though.

project.json:
    "Serilog": "2.3.0",
    "Serilog.Extensions.Logging": "1.4.0",
    "Serilog.Enrichers.Environment": "2.0.0",
    "Serilog.Enrichers.Process": "2.0.0",
    "Serilog.Enrichers.Thread": "2.0.0",
    "Serilog.Sinks.RollingFile": "2.0.0",
    "Serilog.Sinks.Seq": "2.0.0",
    "Serilog.Sinks.ColoredConsole": "2.0.0",
    "Serilog.Settings.Configuration": "2.2.0"

config.json:
  "Serilog": {
    "Using": [ "Serilog.Sinks.RollingFile" ],
    "MinimumLevel": "Debug",
    "WriteTo": [
      {
        "Name": "RollingFile",
        "Args": {
          "pathFormat": "c:\\logs\\application\\log-{Date}.json",
          "formatter": "Serilog.Formatting.Json.JsonFormatter, Serilog",
          "retainedFileCountLimit": "7"
        }
      }
    ],
    "Enrich": [ "WithMachineName", "WithThreadId", "WithProcessId" ]
  }

Unexpectedly this generates log files in plain text (altho in the expected location!). The JsonFormatter configuration is silently ignored:

2017-03-14 15:18:51.192 +01:00 [Debug] Hosting starting
2017-03-14 15:18:51.394 +01:00 [Debug] Hosting started
2017-03-14 15:18:51.627 +01:00 [Information] Request starting HTTP/1.1 GET http://localhost:49652/  
etc

The app targets the full .NET framework 4.5.1

**Comment by skomis-mm** [comment]
@andersnm , I think you need upgrade `RollingFile` package to at least version 2.1.0
see [this](https://github.com/serilog/serilog-sinks-rollingfile/issues/6)

**Comment by andersnm** [comment]
Obvious indeed, found my own problem after trying some random stuff

It works when updating the rolling file package:
    "Serilog.Sinks.RollingFile": "2.2.0",

Also thanks @skomis-mm
