### ISSUE TITLE
Trouble getting Serilog.Sinks.MsSqlServer config to work

### ISSUE THREAD

**Issue by gthelp** [serilog/serilog-settings-configuration#43]
Do you have a sample for configuring SQL sink?
In my startup have

Log.Logger = new LoggerConfiguration()
                    .WriteTo.MSSqlServer(connectionString: configuration.GetSection("Data")["connectProd:ConnectionString"],
                                    tableName: "Logs",
                                    restrictedToMinimumLevel: LogEventLevel.Warning, autoCreateSqlTable: true) 
                    .Enrich.FromLogContext()
                    .CreateLogger();

Thanks

**Comment by nblumhardt** [comment]
Hello! You can use the quick-fix (Ctrl+.) in Serilog Analyzer https://github.com/Suchiman/SerilogAnalyzer to generate JSON or XML configuration from the code. HTH!

**Comment by RomanKernSW** [comment]
Hi, try this one

```json
{
  "Serilog": {
    "Using": [ "if needed" ],
    "MinimumLevel": "Verbose",
    "Properties": {
      "Environment": "Development"
    },
    "WriteTo": [
      {
        "Name": "MSSqlServer",
        "Args": {
          "connectionString": "Data Source= ...",
          "tableName": "Logs",
          "formatter": "Serilog.Formatting.Json.JsonFormatter, Serilog"
        }
      }
    ]
  } 
}```

just add other parameter to the args ;)

**Comment by MV10** [comment]
@gthelp If you're still having problems, please post the versions of this package and the SQL sink you're using. (Most recent questions in the SQL repository are related to using the wrong packages -- right now you want to use `dev` packages from both).

**Comment by MV10** [comment]
Closing, over a year old, we can re-open if the OP needs additional help.
