### ISSUE TITLE
Setting Args with Enrich

### ISSUE THREAD

**Issue by alexangas** [serilog/serilog-settings-configuration#442]
I'm attempting to use [https://github.com/serilog/serilog-enrichers-environment](https://serilog/serilog-enrichers-environment). The Enrich part of the config I have is:

```
    "Enrich": [
      "FromLogContext",
      "WithMachineName",
      "WithEnvironmentName",
      {
        "Name": "WithEnvironmentVariable",
        "Args": {
          "envVarName": "WEBSITE_SITE_NAME"
        }
      }
    ]
```

Everything comes through except the custom environment variable.

Is this supported, and if so, what am I doing wrong? Thanks!

**Comment by nblumhardt** [comment]
Hi Alex,

The argument name is `environmentVariableName` - this should work AFAIK.

Hope this helps,
Nick

**Comment by alexangas** [comment]
Thanks @nblumhardt - I was looking at the README that has a different variable name, not the actual code 🤦
