### ISSUE TITLE
Custom Sink compatibility

### ISSUE THREAD

**Issue by itlackey** [serilog/serilog-settings-configuration#50]
Hello,

I am in the process of writing a custom sink. Is there anything special I need to do to allow the sink to work with this extension?

Any information is much appreciated!

Thanks!

**Comment by nblumhardt** [comment]
Hi! As long as your sink works with the regular `WriteTo.X()` C# syntax, and accepts simple parameters with types like `string`, `int` and so-on, this will just work 👍

**Comment by itlackey** [comment]
Sorry this got buried under all the other work... Thanks for the information!
