### ISSUE TITLE
How to configure the frequency of logging in serilog ? 

### ISSUE THREAD

**Issue by Harish-Sundaram** [serilog/serilog-settings-configuration#55]
I need to somewhere specify that logs should happen for every 10 seconds or something like that for some reasons, how do I do that.
TIA

**Comment by nblumhardt** [comment]
Hi Harish- this isn't something Serilog itself can do; your app will need to use a `System.Threading.Timer` or similar mechanism to call Serilog every 10 seconds. Hope this helps,
Nick

**Comment by merbla** [comment]
@Harish-Sundaram out of interest, what Serilog sinks are you using?

**Comment by Harish-Sundaram** [comment]
@nblumhardt @merbla  My issue is when writing logs in server it takes a very long time say 10 hrs sometimes a day too and in some cases it does not write at all, but in local it writes immediately, server version is Windows Server 2012 R2, why is it happening like this, is there a workaround, also I used flushTimeToInterval property without buffered property still it does not work.
Need help to resolve this. TIA.

**Comment by merbla** [comment]
Hi @Harish-Sundaram, is this related to the [Rolling File Sink](https://github.com/serilog/serilog-sinks-rollingfile)?

**Comment by Harish-Sundaram** [comment]
@merbla Yes it is. This is my code
```
Serilog.Log.Logger = new LoggerConfiguration()
                .ReadFrom.KeyValuePairs(configValues)
                //Existing
                //.WriteTo.Async(a => a.RollingFile("Log-{Date}", buffered: false))
                //New
                .WriteTo.Async(a => a.RollingFile("Log-{Date}",flushToDiskInterval: TimeSpan.FromSeconds(10)))
                .CreateLogger();
```

I am using Serilog sinks rolling file version : 2.0.0.0

**Comment by nblumhardt** [comment]
Might be necessary to update the rolling file sink version, @Harish-Sundaram.

Please jump in with a comment if you are still experiencing this issue, however we'll need more info (or a repro) to make progress on it I think.
