### ISSUE TITLE
Exception occurs when attempting to override base appsettings.json values

### ISSUE THREAD

**Issue by aarndt** [serilog/serilog-settings-configuration#57]
Hello,

I currently have two appsettings files in my .NET Core application:

appsettings.json
appsettings.development.json

I would like to override logging settings that are defined in appsettings.json, on a per-environment basis. 

Here is the Serilog section in appsettings.json:
```json	
"Serilog": {
  "MinimumLevel": {
    "Default": "Information",
    "Override": {
      "FinanceApp": "Debug",
      "System": "Warning",
      "Microsoft": "Information"
    }
  },
  "WriteTo": [
    {
      "Name": "LiterateConsole"
    },
    {
      "Name": "RollingFile",
      "Args": {
        "pathFormat": "C:\\Log\\App\\log-{Date}.txt"
        }
     }
    ]
  }
```
and appsettings.development.json
```json
"Serilog": {
  "MinimumLevel": {
    "Default": "Information",
    "Override": {
      "FinanceApp": "Information",
      "System": "Warning",
      "Microsoft": "Warning"
    }
  },
  "WriteTo": [
    {
      "Name": "RollingFile",
      "Args": {
        "pathFormat": "C:\\Log\\App\\Development\\log-{Date}.txt"
      }
    }
  ]
}
```
As you can see, in appsettings.development.json, my intention is to remove the LiterateConsole logger, and modify the path of the RollingFile logger. However, when I run the app, I immediate get the following error
```
Unhandled Exception: System.ArgumentException: An item with the same key has already been added. Key: RollingFile
   at System.ThrowHelper.ThrowAddingDuplicateWithKeyArgumentException(Object key)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Serilog.Settings.Configuration.ConfigurationReader.GetMethodCalls(IConfigurationSection directive)
   at Serilog.Settings.Configuration.ConfigurationReader.ApplySinks(LoggerConfiguration loggerConfiguration, Assembly[] configurationAssemblies)
   at Serilog.Configuration.LoggerSettingsConfiguration.Settings(ILoggerSettings settings)
```

If I add the LiterateConsole logger to appsettings.development.json, the error goes away. 

Any help would be greatly appreciated. Please let me know if any other details are needed.

**Comment by skomis-mm** [comment]
@aarndt , first, please update package to the latest version (*2.4* for now) to get rid of exception.
Second, layers of configuration sources are merged. So absence of `LiterateConsole` in the `appsettings.development.json` will not remove that section from the top layer (`appsettings.json`). One way to achieve what you want will be this kind of configuration:
```json
"WriteTo": [
  "",
  {
    "Name": "RollingFile",
    "Args": {
      "pathFormat": "C:\\Log\\App\\Development\\log-{Date}.txt"
    }
  }
]
``` 

Another way is to split `appsettings.json` to a more specific configurations (`appsettings.test.json`, `appsettings.development.json`,..) so that the top layer will always be common for other layers.

**Comment by aarndt** [comment]
This works great. Thank you for your help @skomis-mm
