### ISSUE TITLE
Getting "Argument value should be of type Action<>." with the below appSetting.json

### ISSUE THREAD

**Issue by avireddy02** [serilog/serilog-settings-configuration#58]
Please correct me if i'am doing anything wrong. Also provided working sample config from C# for reference.
```c#
    Log.Logger = new LoggerConfiguration()
                .MinimumLevel.Debug()
                .WriteTo.EventCollector("http://localhost:8088/services/collector",
                                                    "CCFAF2DW-E893-45E9-AB39-BC6D8DER485C", 
                        new CompactSplunkJsonFormatter(host:"localhost"))
                .CreateLogger();
````

```json
{ 
  "Serilog": {
    "MinimumLevel": {
      "Default": "Information",
      "Override": {
        "Microsoft": "Warning",
        "System": "Error"
      }
    },
    "WriteTo": [
      {
        "Name": "EventCollector",
        "Args": {
          "splunkHost": "http://localhost:8088/services/collector/event",
          "eventCollectorToken": "CCFAF2DW-E893-45E9-AB39-BC6D8DER485C",
          "jsonFormatter": [
            {
              "Name": "Serilog.Sinks.Splunk.CompactSplunkJsonFormatter, Serilog.Sinks.Splunk",
              "Args": {
                "host": "localhost" 
              }
            }
          ]
        }
      }
    ],
    "Properties": {
      "Application": "LoggingSample"
    }
  }
}

```

**Comment by nblumhardt** [comment]
Hi @avireddy02 - the `jsonFormatter` argument needs to be a string - fully-qualified type name - and the value will always be created using its default constructor. There's no opportunity to pass things through like the `"localhost"` parameter, as things are implemented today.

HTH,
Nick

**Comment by avireddy02** [comment]
@nblumhardt thx for the quick turn around.. do you have any plans to support this in near future?

**Comment by nblumhardt** [comment]
Not at present, though it'd be nice to look into.

**Comment by softlion** [comment]
Same problem with the Http sink and its Options object.

**Comment by axelheer** [comment]
I'm trying to use this for custom column options for the SQL sink. Any help would be great.

Since it should be possible (?) to specify a qualified type, which gets instantiated using its default constructor, let's misuse inheritance:

    public class LegacyColumns : ColumnOptions
    {
        public LegacyColumns()
        {
            TimeStamp.ColumnName = "Date";

            Store.Remove(StandardColumn.Properties);
            Store.Remove(StandardColumn.MessageTemplate);
        }
    }

Given the above discussion I'd give the following JSON a try:

    {
      "Name": "MSSqlServer",
      "Args": {
        "connectionString": "Data Source=(localdb)\\MSSQLLocalDB;Initial Catalog=Narf;Integrated Security=True;",
        "tableName": "Log",
        "columnOptions": { "Name": "Narf.LegacyColumns, Narf" }
      }
    },

But that leads to the same `InvalidOperationException` as above.

Any ideas?

**Comment by nblumhardt** [comment]
@axelheer nice workaround! :-) The issue thwarting you is #71.

Ideally we should support fully-qualified type names, but perhaps also something like:

```json
{ "$type": "Foo, Foo", "Name": "Bar" }
```

...to create more complex objects.

**Comment by skomis-mm** [comment]
This is now working OOB with `3.0`+ releases.
