### ISSUE TITLE
ASP.NET 4.6 MVC App, cannot configure Serilog...

### ISSUE THREAD

**Issue by KeithBarrows** [serilog/serilog-settings-configuration#61]
I am trying to use the JSON appsettings file in a f/x 4.6 class project.

	using System;
	using System.IO;
	using System.Globalization;
	using System.Linq;
	using Serilog;
	using Serilog.Context;
	using Serilog.Core;
	using Microsoft.Extensions.Configuration;
	using LogLevelSerilog = Serilog.Events.LogEventLevel;

	namespace Logging.Serilogger
	{
		public class SerilogLogger : LoggerBase
		{
			#region Fields
			public LoggingLevelSwitch LevelSwitch { get; set; }
			public ILogger CurrentLogger { get; }
			public LogLevelSerilog MinimumLevel { get; set; }
			#endregion

			protected internal SerilogLogger(ILogger logger = null)
			{
				if (logger != null)
				{
					CurrentLogger = logger;
					return;
				}

				if (LevelSwitch == null)
				{
					LevelSwitch = new LoggingLevelSwitch { MinimumLevel = LogLevelSerilog.Information };
				}

				var configuration = new ConfigurationBuilder()
					.SetBasePath(Directory.GetCurrentDirectory())
					.AddJsonFile(path: "appsettings.json", optional: false, reloadOnChange: true)
					.Build();

				Log.Logger = new LoggerConfiguration()
					.ReadFrom.Configuration(configuration)
					.CreateLogger();

				//.MinimumLevel.ControlledBy(LevelSwitch)
				//.Enrich.With<HttpRequestIdEnricher>()
				//.Enrich.With<HttpSessionIdEnricher>()
				//.Enrich.With<ClaimValueEnricher>()
				//.Enrich.With<ThreadIdEnricher>()
				//.Enrich.FromLogContext()
				//.WriteTo.Seq("http://localhost:5341") 
				//// Filter to a sublogger for instrumentation and PII free data...
				//.WriteTo.Logger(lc => lc.MinimumLevel.Information()
				//						.WriteTo.Seq("http://localhost:5342"))
				//.CreateLogger();

				CurrentLogger = Log.Logger;
			}
		...
		}
	}

I know this is simple but I am not finding the solution.  I am getting this build error:

> Error	CS1061	'ConfigurationBuilder' does not contain a definition for 'SetBasePath' and no extension method 'SetBasePath' accepting a first argument of type 'ConfigurationBuilder' could be found (are you missing a using directive or an assembly reference?)	

I have a lot of config info I would like external to the app so it can be changed "on the fly".  I am also planning on using 1 or 2 sub-loggers, restricting what can go to the sub-loggers.  Before I can do that, I need to get the external configuration working correctly.  The files were from a Nuget and it appears it chose the correct framework so I am fairly certain I am dealing with the build that had these settings when built:

	"net4.6": {
	   "buildOptions": {
		 "preserveCompilationContext": true
	   }
	},

All Nugets are up to date as of 5 July, 2017.

Can you (or anyone) point me in the right direction?

TIA

**Comment by nblumhardt** [comment]
Hi Keith, thanks for getting in touch.

If you download/check out the repo, there's a sample application in https://github.com/serilog/serilog-settings-configuration/tree/dev/sample/Sample that includes the `SetBasePath()` call. You might be able to F12 your way to its definition, to see which package is bringing it in, etc.

HTH!

**Comment by KeithBarrows** [comment]
Unfortunately, while at work, I do not have access to VS[latest].  The solution is not opening in VS2015.

If I comment out the .SetBasePath then it errors out on build as the .AddJsonFile is not recognized.  I am missing *something*, for sure.  Will keep poking.

**Comment by KeithBarrows** [comment]
Another day, and still I cannot find what I am missing.

**Comment by skomis-mm** [comment]
@KeithBarrows, try to install `Microsoft.Extensions.Configuration.Json` package

**Comment by KeithBarrows** [comment]
I think that did it.  Also came with a few more dependencies, added those as well, now chugging on to the next obstacle to this learning curve.  

Thanks!  Correct answer:  add (Nuget package) for 

> Microsoft.Extensions.Configuration.Json
