### ISSUE TITLE
Columoptions missing for logs.. unable to query or get insights from logs- azure table storage sink

### ISSUE THREAD

**Issue by pmaheshgupta** [serilog/serilog-settings-configuration#65]
Hi,
Is there any roadmap to implement column options to map log data to columns in azure table storage sink.
with the available functionality unable to query data based on log attributes, like stack trace or inner exception to a column.

It will be a very usefull feature for logging.

**Comment by nblumhardt** [comment]
This and #58 appear to require the same feature - creating complex objects as parameter types. I'm going to close this as duplicate, but please jump in on the other issue with your thoughts. Thanks for getting in touch!
