### ISSUE TITLE
Trying to add Source and ThreadId doesn't seem to work in dotnetcore

### ISSUE THREAD

**Issue by jimmymain** [serilog/serilog-settings-configuration#68]
My configuration is as follows:

```
                var columns = new ColumnOptions
                {
                    AdditionalDataColumns = new Collection<DataColumn>
                {
                    new DataColumn { DataType = typeof(string), ColumnName = "UserName" },
                    new DataColumn { DataType = typeof(string), ColumnName = "ThreadId" },
                    new DataColumn { DataType = typeof(string), ColumnName = "Source" }
                }
                };
                var cs = GetConnectionString();
                Log.Logger = new LoggerConfiguration()
                           .MinimumLevel.Debug()
                           .MinimumLevel.Override("Microsoft", LogEventLevel.Warning)
                           .Enrich.FromLogContext()
                           .WriteTo.Console()
                           .WriteTo.MSSqlServer(
                                cs,
                                "Logs",
                                LogEventLevel.Information,
                                autoCreateSqlTable: true,
                                columnOptions: columns)
                           .CreateLogger();
                BuildWebHost(args).Run();
```

I am using dotnetcore 2.

The threadid and source columns are always blank, though UserName surprisingly works without adding further enrichment.

How do I get the thread and source populating on dotnetcore.

**Comment by nblumhardt** [comment]
Hi @jimmymain - thanks for getting in touch.

I'm also surprised there's a value in `UserName`, not sure what's going on there.

For source, you might need to change the column name to `SourceContext` - this would then receive values logged through type-specific loggers like `Log.ForContext<Program>().Information("Hello")`.

For `ThreadId`, see the Serilog.Enrichers.Thread package.

HTH,
Nick

**Comment by jimmymain** [comment]
Hi,

I am trying to log the user name.
I have tried this?

Unfortunately in this example the user is authenticated, but ActiveUser is logged as null, so it's too late in the pipeline even for the log?

```
            app.UseIdentityServer();
            app.UseAuthentication();

            app.Use(async (httpContext, next) =>
                            {
                                await next.Invoke();
                                var userName = httpContext.User.Identity.IsAuthenticated 
                                ? httpContext.User.GetClaim("email")
                                : "(unknown)";
                                LogContext.PushProperty("ActiveUser", !string.IsNullOrWhiteSpace(userName) ? userName : "(unknown)");
                            });
```

and this

In this example the user is never authenticated.

```   
            app.UseIdentityServer();
            app.UseAuthentication();

         app.Use(async (httpContext, next) =>
                            {
                                var userName = httpContext.User.Identity.IsAuthenticated 
                                ? httpContext.User.GetClaim("email")
                                : "(unknown)";
                                LogContext.PushProperty("ActiveUser", !string.IsNullOrWhiteSpace(userName) ? userName : "(unknown)");
                                await next.Invoke();
                            });
```

**Comment by nblumhardt** [comment]
No ideas, sorry - looks like you may need to debug through your middleware.

One important thing though, `LogContext.PushProperty()` should be in a `using` block, with the `await` inside it.

HTH

**Comment by jimmymain** [comment]
I have debugged through the middleware, and it appears that the JWT bearer token is validated AFTER the app.Use - which makes no sense.

                .AddJwtBearer(
                    _ =>
                    {
                        // this event occurs after the app.Use(async (httpContext ...
                        _.Events = new JwtBearerEvents
                        {
                            OnTokenValidated = context =>
                            {
                                context.Principal = new ClaimsPrincipal(
                                    new ClaimsIdentity(context.Principal.Claims, "local"));
                                return Task.CompletedTask;
                            }
                        };

**Comment by jimmymain** [comment]
I solved it using a [filter](https://stackoverflow.com/questions/46296389/accessing-dotnetcore-middleware-after-a-jwt-token-is-validated).

``` c#
public class ActiveUserFilter : IAsyncActionFilter
{
    public async Task OnActionExecutionAsync(
        ActionExecutingContext context,
        ActionExecutionDelegate next)
    {
        var userName = context.HttpContext.User.Identity.IsAuthenticated
        ? context.HttpContext.User.GetClaim("email")
        : "(unknown)";
        using (LogContext.PushProperty("ActiveUser", !string.IsNullOrWhiteSpace(userName) ? userName : "(unknown)"))
            await next();
    }
}
```

**Comment by nblumhardt** [comment]
Great, thanks for the follow-up. Good luck with the app!
