### ISSUE TITLE
Question - How/can I use settings with reloadOnChange and LoggingLevelSwitch

### ISSUE THREAD

**Issue by dls314** [serilog/serilog-settings-configuration#72]
I'd like to do something like the following. Is it possible?

`appsettings.json`
```
{
  "Serilog": {
    "MinimumLevel": {
      "ControlledBy": {
        "Serilog.Core.LoggingLevelSwitch": "Debug"
      }
    }
  }
}
```

`program.cs`
```
var configuration = new ConfigurationBuilder().SetBasePath(Directory.GetCurrentDirectory())
    .AddJsonFile("appsettings.json", reloadOnChange: true)
    //...
    .Build();

Log.Logger = new LoggerConfiguration()
    .ReadFrom.Configuration(configuration)
    //...
    .CreateLogger();
```

My intent is to modify the config file and have the log level change without restarting the application.

**Comment by nblumhardt** [comment]
Hi Dave, this should just work straight out of the box with the normal `"MinimumLevel": "Debug"` syntax:

https://github.com/serilog/serilog-settings-configuration/blob/dev/src/Serilog.Settings.Configuration/Settings/Configuration/ConfigurationReader.cs#L69

Not having any luck with it?

**Comment by dls314** [comment]
I thought it was a far fetched ask and haven't worked up a test. Thanks for answering :-)
