### ISSUE TITLE
Support for static member as the value of setting using `::`

### ISSUE THREAD

**Issue by tsimbalar** [serilog/serilog-settings-configuration#73]
This is the *Serilog.Settings.Configuration* transposition of serilog/serilog#1057 .

The idea is to support `"Serilog.Sinks.SystemConsole.Themes.AnsiConsoleTheme::Grayscale"` to access a static member for arguments of a complex type.

See details of issue in *core* *Serilog* repo to implement it in a consistent way.

This would help with serilog/serilog-sinks-console#16

**Comment by tsimbalar** [comment]
Merged in #77

**Comment by jp7677** [comment]
Thanks a lot! Could you consider to release a new version?

**Comment by tsimbalar** [comment]
@jp7677 Hi, this is available in nuget package v2.5.0 which was (accidentally 😛 / by yours truly ) generated from the dev branch
