### ISSUE TITLE
How to flush application insights client when using configuration

### ISSUE THREAD

**Issue by lvanderbijl** [serilog/serilog-settings-configuration#76]
Is there a way to set up message flushing through the configuration?

When using applicatijon insights, you need to flush the logger before shutdown (or use a persistent channel) in order to ensure messages are always delivered to app insights.

See here: https://github.com/serilog/serilog-sinks-applicationinsights

Is there any way to configure this through configuration?

**Comment by MV10** [comment]
Flushing is handled by the core Serilog package and at this time there aren't any configuration options.

If the App Insights sink isn't flushing, that sounds like an issue that should be opened in that repository.

I did run into a situation where flushing didn't happen when running in debug in an ASP.NET Core app in VS2017, despite having a `Log.FlushAndClose` call in a `finally` block in Kestrel's `main()`. Microsoft explained that when VS decides you're finished debugging (typically by closing the browser), it does a process-kill on the app. This is an immediate shutdown, things like `Dispose` and `finally` blocks are not executed. So if that sounds like your case, you might check whether it flushes properly running stand-alone.

**Comment by MV10** [comment]
Closing, not an issue specific to configuration.
