### ISSUE TITLE
Possible memory leak.

### ISSUE THREAD

**Issue by Boombasteg** [serilog/serilog-settings-configuration#85]
Hello!

We are using Serilog in our AspNetCore WebApi app in ServiceFabric.
appsettings.json is configured like in [your sample](https://github.com/serilog/serilog-settings-configuration).

The memory leak is happening when exceptions are occured (in Startup.cs).

Please see [sample project](https://github.com/Boombasteg/SerilogMemoryLeak).
Just publish it to SF and observe WebCore.exe memory in Task Manager.

**Comment by khellang** [comment]
This is a know issue with the ASP.NET Core hosting/container and has been fixed for 2.1; https://github.com/aspnet/Hosting/issues/1313.

They also found this while hosting in SF:

> The issue is amplified by Service Fabric, because it retries starting the web app/API without starting a new process, so the leak becomes more apparent. In our case, this lead to a high CPU hang which disabled some production level machines.

**Comment by Boombasteg** [comment]
Ok. Thank you!

**Comment by khellang** [comment]
I'll close this issue as it's not related to Serilog (there's nothing we can do about it), and we can follow https://github.com/aspnet/Hosting/issues/1313.

What ASP.NET Core version are you using? Hopefully they'll backport the fix to 2.x and 1.x 😄

**Comment by Boombasteg** [comment]
We are using 2.0.1. Will waiting 2.1 and update 
Now we use hack to avoid memory leaks:
```
catch (SqlException e)
{
    Process.GetCurrentProcess().Kill();
}
```
 :)
