### ISSUE TITLE
Cant load custom sink from appsettings.json

### ISSUE THREAD

**Issue by MartyBJones** [serilog/serilog-settings-configuration#86]
I have written a custom Sink that works fine if I configure it in Program.cs.  I attempted to configure the Sink using appsettings.json and it fails to find my sink.  The sink is in it's own class library and the class library is referenced in the solution as well as set as a dependency on the test console app I am using.  The class library as well as the test console app are both .Net Core 2.  The error that I receive is "**Could not load file or assembly 'EaSerilogSink.EnterpriseActivitySerilogSink, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.**'". 

Here is my configuration file:

`{
  "Serilog": {
    "Using": [ "EaSerilogSink.EnterpriseActivitySerilogSink" ],
    "MinimumLevel": {
      "Default": "Debug",
      "Override": {
        "Microsoft": "Warning",
        "System": "Error"
      }
    },
    "WriteTo": [
      {
        "Name": "EnterpriseActivitySerilogSink",
        "Args": [
          { "applicationId": "MyTestApp" },
          { "directory": "c:\\activitylog\\service" }
        ]
      }
    ],
    "Enrich": [ "FromLogContext", "WithMachineName" ]
  }
}`

Any ideas why it can't find the assembly?

**Comment by tsimbalar** [comment]
Hi Marty,

What you describe should work in theory :p

just to be sure, can you confirm that the assembly name of your class library is `EaSerilogSink.EnterpriseActivitySerilogSink` (it may be different from the root namespace) ? 

Could you copy/paste the contents of your csproj files ? (both the class library and the console app)

Thanks !

**Comment by MartyBJones** [comment]
That could my issue.  So the "Using" section should be the assembly name of my class library correct?  I checked and my assembly name is "EaSerilogSink".  Do I need to fully qualify the Sink Name in the WriteTo section?

**Comment by MartyBJones** [comment]
Here is the .csproj file for my class library:
`<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="10.0.3" />
    <PackageReference Include="Serilog" Version="2.6.0" />
  </ItemGroup>

</Project>
`

Here is the .csproj file for my console app:

`<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="2.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="2.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="2.0.0" />
    <PackageReference Include="Serilog" Version="2.6.0" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="2.4.1-dev-00072" />
    <PackageReference Include="Serilog.Sinks.Console" Version="3.1.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EaSerilogSink\EaSerilogSink.csproj">
      <Private></Private>
    </ProjectReference>
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
`

**Comment by tsimbalar** [comment]
Hi Marty,

yes, the `Using` should contain just the assembly name, and I believe it does not need to be fully qualified (see example here : https://github.com/tsimbalar/serilog-settings-comparison/tree/master/docs#sinks---basics ).

(the namespace does not really matter, the *configuration* will look for extension methods to `LoggerSinkConfiguration` and similar).

**Comment by MartyBJones** [comment]
Thank you for the link!  That fixed my issue.  Once I set the "Using" property to use the Assembly name and fixed the syntax on the WriteTo -> Arguments property it loads correctly!

**Comment by manjunathdl66** [comment]
Hi Marty,

Could you please share me some example to create custom sink and call through config.json file
