### ISSUE TITLE
Question: Different Overrides for sinks?

### ISSUE THREAD

**Issue by dudleycodes** [serilog/serilog-settings-configuration#93]
Using `appsettings.{env}.json` is it possible to specify different overrides for sinks?

Pseudo-code illustrating my thoughts:
```
{
   ...
   "Serilog":{
      "WriteTo":[
         {
            "Name":"Elasticsearch",
            "Args":{
               "nodeUris":"http://localhost:9090",
               "inlineFields":true,
               "minimumLogEventLevel": {
                  "Default":"Information",
                  "Override":{
                     "Microsoft":"Warning"
                  }
               }
            }
         },
         {
            "Name":"Console"
         }
      ],
      "MinimumLevel":{
         "Default":"Information",
         "Override":{
            "System":"Warning"
         }
      },
      "Enrich":[
         "FromLogContext"
      ]
   }
}
```

**Comment by MV10** [comment]
The Serilog configuration packages (all of them) just look for a `LoggerConfiguration` extension method that matches the argument list for a given `WriteTo` entry. (In other words, if you can't do it through code, you can't do it through any of Serilog's configuration packages, either.)

That means, technically, it depends on the sink you're configuring, but the couple of sinks I just checked only support a `LogEventLevel` (which is an enumeration, there is nothing that could match anything like the pseudo-code you posted). Override support would most likely be implemented as two separate arguments (the source and the level), and it doesn't appear that anyone has written any of the sinks that way.

**Comment by mochangping** [comment]
Hi, were you able to solve this issue? @dudleycodes

**Comment by dudleycodes** [comment]
@mochangping Can't say I did.

**Comment by nblumhardt** [comment]
Via code, [conditional sinks in Serilog 2.9-*](https://github.com/serilog/serilog/blob/dev/test/Serilog.Tests/LoggerConfigurationTests.cs#L728) simplify this a bit. It's unlikely this will get direct support in JSON configuration in the near future. HTH!

**Comment by AkosLukacs** [comment]
Looks like you can do it (using latest version of everything & only JSON config):
```json
"Serilog": {
	"MinimumLevel": "Information",
	"WriteTo": [
		{
			"Name": "Console",
			"Args:": {}
		},
		{
			"Name": "EventLog",
			"Args": {
				"restrictedToMinimumLevel": "Warning",
				"manageEventSource": false,
				"source": "xxxxx"
			}
		},
		{
			"Name": "RollingFile",
			"Args": {
				"pathFormat": "logs/xxx-{Date}.log",
				"fileSizeLimitBytes": 10000000,
				"retainedFileCountLimit": 100
			}
		},
		{
			"Name": "Email",
			"Args": {
				"restrictedToMinimumLevel": "Warning",
				"fromEmail": "xxx",
				"toEmail": "xxx",
				"mailServer": "localhost"
			}
		}
	]
}
```

Email & Eventlog only gets warnings & errors, console and rolling file gets everything!

**Comment by ckarcz** [comment]
`"minimumLogEventLevel": {
                  "Default":"Information",
                  "Override":{
                     "Microsoft":"Warning"
                  }
               }`

+1. this kind of configuring would be absolutely ideal. especially for console logs where you may want *some* info level logs (like service starting, stopping, etc) and rest defaulted to warning/error..

**Comment by skomis-mm** [comment]
@ckarcz ,

Sinks cannot lower log level bar set by default minimum level and overrides, but only raise / restrict log level via `restrictedToMinimumLevel` parameter. 

The limited solution to accomplish desired effect is to set the highest of the minimum acceptable levels to a default minimum level and use subloggers with filters or conditional sinks (2.9+) mentioned by @nblumhardt , but it will be less effective.

For example, in combination with `Serilog.Filters.Expression` using conditional sinks configuration can look like:
```json
"MinimumLevel": {
  "Default": "Verbose"
},
"WriteTo": [
  {
    "Name": "Conditional",
    "Args": {
      "expression": "@Level in ['Warning', 'Error', 'Fatal'] and StartsWith(SourceContext, 'Microsoft')",
      "configureSink": [ "Console" ]
    }
  },
  {
    "Name": "File",
    "Args": { "path": "c:/temp/log.txt" }
  }
],
```
