### ISSUE TITLE
Unable to specify a string array

### ISSUE THREAD

**Issue by farzadmf** [serilog/serilog-settings-configuration#98]
Hi,

I'm using `Serilog.Sinks.AzureTableStorage` package and more specifically, the `WriteTo.AzureTableStorageWithProperties`, which accepts a `propertyColumns` argument, which is of type `string[]`.

No matter what I tried, I can't make it work so that I can pass an array of strings in my `appsettings.json` (or using the colon-separated syntax from my environment variables).

I tried doing something like this in `appsettings.json`:

```js
WriteTo: [
  // ...
  {
    "Name": "AzureTableStorageWithProperties",
    "Args": {
      // ...
      "propertyColumns": [ "Column1", "Column2" ]
    }
  }
]
```

But I get an error saying that `Argument value should be of type Action<>`.

I tried this: `"propertyColumns": "Column1, Column2"`, but this one also blows.

I also tried using environment variables, e.g.:

```
Serilog:WriteTo:2:Args:propertyColumns:0="Column1"
Serilog:WriteTo:2:Args:propertyColumns:1="Column2"
```

But, again no luck :(

So, is it possible somehow to specify a string array using this library? If so, what am I missing here?

I would really, really appreciate if you help me out here

**Comment by farzadmf** [comment]
Sorry if I'm asking a stupid question, but are these changes available in the NuGet package? Version 2.6.1 seems to be too old to contain these changes. Is it released as a pre-release version?

**Comment by nblumhardt** [comment]
https://www.nuget.org/packages/Serilog.Settings.Configuration/3.0.0-dev-00103 is the one you're looking for 👍

**Comment by farzadmf** [comment]
Thank you @nblumhardt ; I'll check that out
