### ISSUE TITLE
Unreachable code in StringArgumentValue / review support for dynamic config changes

### ISSUE THREAD

**Issue by MV10** [serilog/serilog-settings-configuration#99]
(Figured I'd re-use this issue thread I opened accidentally... lol)

Anyway, the `ConvertTo` method in the `StringArgumentValue` class has unreachable code.

At the start of the method ([lines 37-40](https://github.com/serilog/serilog-settings-configuration/blob/dev/src/Serilog.Settings.Configuration/Settings/Configuration/StringArgumentValue.cs#L37-L40)) it converts the argument value when the requested type is `LoggingLevelSwitch`:

```csharp
if (toType == typeof(LoggingLevelSwitch))
{
    return declaredLevelSwitches.LookUpSwitchByName(argumentValue);
}
```

Then way down at the end of the method ([lines 116-139](https://github.com/serilog/serilog-settings-configuration/blob/dev/src/Serilog.Settings.Configuration/Settings/Configuration/StringArgumentValue.cs#L116-L139)) there's a larger, completely different block of code for processing `LoggingLevelSwitch`.

I haven't done anything too complicated with the level switches so I'll leave it to somebody else to figure out if the second block is just old leftover code, or if they need to be combined somehow, etc.

**Comment by tsimbalar** [comment]
Ouch, this may be a regression I introduced as part of #88  :-/ 

I think there was at some point some support for detecting changes to the config file and updating the value of `LoggingLevelSwitches` , but I'm not sure exactly what the expected behavior was ... 

Maybe @skomis-mm  knows a bit better ?
